const Database = require('better-sqlite3');
const path = require('path');
const db = new Database(path.join(__dirname, 'camp.db'));
db.pragma('journal_mode = WAL');

// Create tables
db.exec(`
  CREATE TABLE IF NOT EXISTS campers (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    ptft TEXT DEFAULT '',
    paid TEXT DEFAULT '',
    enrollment TEXT DEFAULT '',
    parent TEXT DEFAULT '',
    email TEXT DEFAULT '',
    phone TEXT DEFAULT '',
    age INTEGER DEFAULT 0,
    city TEXT DEFAULT '',
    sex TEXT DEFAULT '',
    allergies TEXT DEFAULT '',
    tshirt TEXT DEFAULT '',
    notes TEXT DEFAULT '',
    special_notes TEXT DEFAULT '',
    weeks TEXT DEFAULT '',
    week1 INTEGER DEFAULT 0,
    week2 INTEGER DEFAULT 0,
    week3 INTEGER DEFAULT 0,
    week4 INTEGER DEFAULT 0,
    week5 INTEGER DEFAULT 0,
    week6 INTEGER DEFAULT 0,
    week7 INTEGER DEFAULT 0,
    week8 INTEGER DEFAULT 0,
    reg_date TEXT DEFAULT '',
    status TEXT DEFAULT 'lead',
    created_at TEXT DEFAULT (datetime('now')),
    updated_at TEXT DEFAULT (datetime('now'))
  );
  CREATE TABLE IF NOT EXISTS comps (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    paid TEXT DEFAULT 'C',
    parent TEXT DEFAULT '',
    email TEXT DEFAULT '',
    phone TEXT DEFAULT '',
    age INTEGER DEFAULT 0,
    city TEXT DEFAULT '',
    sex TEXT DEFAULT '',
    allergies TEXT DEFAULT '',
    weeks TEXT DEFAULT '',
    status TEXT DEFAULT 'comp'
  );
`);

const existing = db.prepare('SELECT COUNT(*) as c FROM campers').get().c;
if (existing > 0) { console.log('Database already seeded (' + existing + ' campers). Skipping.'); process.exit(0); }

console.log('Seeding database with 157 campers...');

const insertCamper = db.prepare(`
  INSERT INTO campers (name,ptft,paid,enrollment,parent,email,phone,age,city,sex,allergies,tshirt,notes,special_notes,weeks,week1,week2,week3,week4,week5,week6,week7,week8,reg_date,status)
  VALUES (@name,@ptft,@paid,@enrollment,@parent,@email,@phone,@age,@city,@sex,@allergies,@tshirt,@notes,@special_notes,@weeks,@week1,@week2,@week3,@week4,@week5,@week6,@week7,@week8,@reg_date,@status)
`);

const seedCampers = db.transaction((rows) => {
  for (const c of rows) {
    const wa = c.weeks_arr || [0,0,0,0,0,0,0,0];
    insertCamper.run({
      name: c.name, ptft: c.ptft||'', paid: c.paid||'', enrollment: c.enrollment||'',
      parent: c.parent||'', email: c.email||'', phone: c.phone||'',
      age: c.age||0, city: c.city||'', sex: c.sex||'',
      allergies: c.allergies||'', tshirt: c.tshirt||'',
      notes: c.notes||'', special_notes: c.special_notes||'',
      weeks: c.weeks||'',
      week1:wa[0]||0, week2:wa[1]||0, week3:wa[2]||0, week4:wa[3]||0,
      week5:wa[4]||0, week6:wa[5]||0, week7:wa[6]||0, week8:wa[7]||0,
      reg_date: c.reg_date||'', status: c.status||'lead'
    });
  }
});

const camperData = [
  {
    "id": 3,
    "name": "Alana Frazier",
    "ptft": "",
    "paid": "",
    "enrollment": "",
    "parent": "",
    "email": "",
    "phone": "",
    "age": 0,
    "city": "",
    "sex": "",
    "wr": "",
    "allergies": "",
    "tshirt": "",
    "notes": "",
    "weeks": "",
    "weeks_arr": [
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0
    ],
    "reg_date": "",
    "special_notes": "",
    "is_emailed": true,
    "status": "lead"
  },
  {
    "id": 4,
    "name": "Alexander Sanchez",
    "ptft": "",
    "paid": "",
    "enrollment": "",
    "parent": "",
    "email": "",
    "phone": "",
    "age": 0,
    "city": "",
    "sex": "",
    "wr": "",
    "allergies": "",
    "tshirt": "",
    "notes": "",
    "weeks": "",
    "weeks_arr": [
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0
    ],
    "reg_date": "",
    "special_notes": "",
    "is_emailed": true,
    "status": "lead"
  },
  {
    "id": 5,
    "name": "Alexiah Sanchez",
    "ptft": "",
    "paid": "",
    "enrollment": "",
    "parent": "",
    "email": "",
    "phone": "",
    "age": 0,
    "city": "",
    "sex": "",
    "wr": "",
    "allergies": "",
    "tshirt": "",
    "notes": "",
    "weeks": "",
    "weeks_arr": [
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0
    ],
    "reg_date": "",
    "special_notes": "",
    "is_emailed": true,
    "status": "lead"
  },
  {
    "id": 6,
    "name": "Amelia Muso",
    "ptft": "FT",
    "paid": "yes",
    "enrollment": "yes",
    "parent": "Ergen Muso",
    "email": "emuso85@gmail.com",
    "phone": "727-288-7442",
    "age": 10,
    "city": "Windham",
    "sex": "F",
    "wr": "W & R",
    "allergies": "",
    "tshirt": "YL",
    "notes": "",
    "weeks": "1,2,3,4,5,6,7,8",
    "weeks_arr": [
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1
    ],
    "reg_date": "2026-01-10",
    "special_notes": "",
    "is_emailed": false,
    "status": "enrolled"
  },
  {
    "id": 7,
    "name": "Amir Cabreja",
    "ptft": "PT",
    "paid": "yes",
    "enrollment": "yes",
    "parent": "Kionys Cabrera",
    "email": "kionyscabrera@yahoo.com",
    "phone": "603-560-1831",
    "age": 8,
    "city": "Salem",
    "sex": "M",
    "wr": "W & R",
    "allergies": "",
    "tshirt": "YM",
    "notes": "",
    "weeks": "3,4,6,7",
    "weeks_arr": [
      0,
      0,
      1,
      1,
      0,
      1,
      1,
      0
    ],
    "reg_date": "2026-02-09",
    "special_notes": "",
    "is_emailed": false,
    "status": "enrolled"
  },
  {
    "id": 8,
    "name": "Andrew Greenleaf",
    "ptft": "PT",
    "paid": "yes",
    "enrollment": "yes",
    "parent": "Kaitlyn Greenleaf",
    "email": "kgreenleaf2@gmail.com",
    "phone": "978-987-0657",
    "age": 8,
    "city": "Windham",
    "sex": "M",
    "wr": "W & R",
    "allergies": "amoxicillin",
    "tshirt": "YL",
    "notes": "taking Linzess and Myrbetriq",
    "weeks": "8",
    "weeks_arr": [
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      1
    ],
    "reg_date": "2026-02-04",
    "special_notes": "",
    "is_emailed": false,
    "status": "enrolled"
  },
  {
    "id": 9,
    "name": "Andrew (AJ) Vincent",
    "ptft": "PT",
    "paid": "yes",
    "enrollment": "yes",
    "parent": "Rebecca Vincent",
    "email": "rebecc5506@gmail.com",
    "phone": "508-725-1953",
    "age": 13,
    "city": "Methuen",
    "sex": "M",
    "wr": "W & R",
    "allergies": "sesame seeds, peanuts",
    "tshirt": "AM",
    "notes": "taking Depakote; autistic",
    "weeks": "3,4,5,6,8",
    "weeks_arr": [
      0,
      0,
      1,
      1,
      1,
      1,
      0,
      1
    ],
    "reg_date": "2026-01-27",
    "special_notes": "",
    "is_emailed": true,
    "status": "enrolled"
  },
  {
    "id": 10,
    "name": "Annie Freiner",
    "ptft": "",
    "paid": "",
    "enrollment": "",
    "parent": "",
    "email": "",
    "phone": "",
    "age": 0,
    "city": "",
    "sex": "",
    "wr": "",
    "allergies": "",
    "tshirt": "",
    "notes": "",
    "weeks": "",
    "weeks_arr": [
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0
    ],
    "reg_date": "",
    "special_notes": "",
    "is_emailed": true,
    "status": "lead"
  },
  {
    "id": 11,
    "name": "Anthony Pacheco",
    "ptft": "PT",
    "paid": "yes",
    "enrollment": "yes",
    "parent": "Michelle Pacheco",
    "email": "mish22288@aol.com",
    "phone": "782-475-7001",
    "age": 11,
    "city": "Methuen",
    "sex": "M",
    "wr": "W & R",
    "allergies": "",
    "tshirt": "YM",
    "notes": "",
    "weeks": "1,3,4,5,7,8",
    "weeks_arr": [
      1,
      0,
      1,
      1,
      1,
      0,
      1,
      1
    ],
    "reg_date": "2026-03-10",
    "special_notes": "",
    "is_emailed": false,
    "status": "enrolled"
  },
  {
    "id": 12,
    "name": "Ara Yeghiazarians",
    "ptft": "",
    "paid": "",
    "enrollment": "",
    "parent": "",
    "email": "",
    "phone": "",
    "age": 0,
    "city": "",
    "sex": "",
    "wr": "",
    "allergies": "",
    "tshirt": "",
    "notes": "",
    "weeks": "",
    "weeks_arr": [
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0
    ],
    "reg_date": "",
    "special_notes": "",
    "is_emailed": true,
    "status": "lead"
  },
  {
    "id": 13,
    "name": "Arthur Comee",
    "ptft": "",
    "paid": "",
    "enrollment": "",
    "parent": "",
    "email": "",
    "phone": "",
    "age": 0,
    "city": "",
    "sex": "",
    "wr": "",
    "allergies": "",
    "tshirt": "",
    "notes": "",
    "weeks": "",
    "weeks_arr": [
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0
    ],
    "reg_date": "",
    "special_notes": "",
    "is_emailed": true,
    "status": "lead"
  },
  {
    "id": 14,
    "name": "Aubrey Nicolosi",
    "ptft": "",
    "paid": "",
    "enrollment": "",
    "parent": "",
    "email": "",
    "phone": "",
    "age": 0,
    "city": "",
    "sex": "",
    "wr": "",
    "allergies": "",
    "tshirt": "",
    "notes": "",
    "weeks": "",
    "weeks_arr": [
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0
    ],
    "reg_date": "",
    "special_notes": "",
    "is_emailed": true,
    "status": "lead"
  },
  {
    "id": 15,
    "name": "Austin Pitta",
    "ptft": "PT",
    "paid": "yes",
    "enrollment": "yes",
    "parent": "Ylan Pitta",
    "email": "ylan.pitta@gmail.com",
    "phone": "6036898901",
    "age": 5,
    "city": "Andover",
    "sex": "M",
    "wr": "W & R",
    "allergies": "",
    "tshirt": "YS",
    "notes": "",
    "weeks": "3",
    "weeks_arr": [
      0,
      0,
      1,
      0,
      0,
      0,
      0,
      0
    ],
    "reg_date": "2026-01-14",
    "special_notes": "",
    "is_emailed": false,
    "status": "enrolled"
  },
  {
    "id": 16,
    "name": "Avery O'Brien",
    "ptft": "PT",
    "paid": "yes",
    "enrollment": "failed",
    "parent": "Melissa Atwood",
    "email": "matwood1985@gmail.com",
    "phone": "978-289-7882",
    "age": 10,
    "city": "North Andover",
    "sex": "F",
    "wr": "W & R",
    "allergies": "",
    "tshirt": "YL",
    "notes": "",
    "weeks": "1,8",
    "weeks_arr": [
      1,
      0,
      0,
      0,
      0,
      0,
      0,
      1
    ],
    "reg_date": "2026-01-19",
    "special_notes": "",
    "is_emailed": true,
    "status": "enrolled"
  },
  {
    "id": 17,
    "name": "Benjamin Cyr",
    "ptft": "",
    "paid": "",
    "enrollment": "",
    "parent": "",
    "email": "",
    "phone": "",
    "age": 0,
    "city": "",
    "sex": "",
    "wr": "",
    "allergies": "",
    "tshirt": "",
    "notes": "",
    "weeks": "",
    "weeks_arr": [
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0
    ],
    "reg_date": "",
    "special_notes": "",
    "is_emailed": true,
    "status": "lead"
  },
  {
    "id": 18,
    "name": "Benjamin Kelloway",
    "ptft": "",
    "paid": "",
    "enrollment": "",
    "parent": "",
    "email": "",
    "phone": "",
    "age": 0,
    "city": "",
    "sex": "",
    "wr": "",
    "allergies": "",
    "tshirt": "",
    "notes": "",
    "weeks": "",
    "weeks_arr": [
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0
    ],
    "reg_date": "",
    "special_notes": "",
    "is_emailed": true,
    "status": "lead"
  },
  {
    "id": 19,
    "name": "Benjamin Kim",
    "ptft": "",
    "paid": "",
    "enrollment": "",
    "parent": "",
    "email": "",
    "phone": "",
    "age": 0,
    "city": "",
    "sex": "",
    "wr": "",
    "allergies": "",
    "tshirt": "",
    "notes": "",
    "weeks": "",
    "weeks_arr": [
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0
    ],
    "reg_date": "",
    "special_notes": "",
    "is_emailed": true,
    "status": "lead"
  },
  {
    "id": 20,
    "name": "Bennett Goodhue",
    "ptft": "PT",
    "paid": "yes",
    "enrollment": "no",
    "parent": "Krystyne Goodhue",
    "email": "krystyne787@gmail.com",
    "phone": "978-821-7266",
    "age": 8,
    "city": "Methuen",
    "sex": "M",
    "wr": "W & R",
    "allergies": "",
    "tshirt": "YM",
    "notes": "",
    "weeks": "2,3,5,6,7,8",
    "weeks_arr": [
      0,
      1,
      1,
      0,
      1,
      1,
      1,
      1
    ],
    "reg_date": "2026-03-19",
    "special_notes": "",
    "is_emailed": true,
    "status": "enrolled"
  },
  {
    "id": 21,
    "name": "Blakely Habib",
    "ptft": "",
    "paid": "",
    "enrollment": "",
    "parent": "",
    "email": "",
    "phone": "",
    "age": 0,
    "city": "",
    "sex": "",
    "wr": "",
    "allergies": "",
    "tshirt": "",
    "notes": "",
    "weeks": "",
    "weeks_arr": [
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0
    ],
    "reg_date": "",
    "special_notes": "",
    "is_emailed": true,
    "status": "lead"
  },
  {
    "id": 22,
    "name": "Bradley Guyotte",
    "ptft": "PT",
    "paid": "yes",
    "enrollment": "yes",
    "parent": "Stephanie Guyotte",
    "email": "scguyotte@gmail.com",
    "phone": "617-678-4094",
    "age": 13,
    "city": "Methuen",
    "sex": "M",
    "wr": "W & R",
    "allergies": "",
    "tshirt": "YXL",
    "notes": "",
    "weeks": "3,4,6,7",
    "weeks_arr": [
      0,
      0,
      1,
      1,
      0,
      1,
      1,
      0
    ],
    "reg_date": "2026-03-16",
    "special_notes": "",
    "is_emailed": false,
    "status": "enrolled"
  },
  {
    "id": 23,
    "name": "Brandon Chu",
    "ptft": "PT",
    "paid": "yes",
    "enrollment": "yes",
    "parent": "Mary Ann Bruce",
    "email": "maryannbruce81@gmail.com",
    "phone": "617-240-5641",
    "age": 0,
    "city": "Methuen",
    "sex": "M",
    "wr": "W & R",
    "allergies": "seasonal",
    "tshirt": "YS",
    "notes": "",
    "weeks": "1,5",
    "weeks_arr": [
      1,
      0,
      0,
      0,
      1,
      0,
      0,
      0
    ],
    "reg_date": "2026-02-09",
    "special_notes": "",
    "is_emailed": false,
    "status": "enrolled"
  },
  {
    "id": 24,
    "name": "Braxton Medugno",
    "ptft": "FT",
    "paid": "",
    "enrollment": "",
    "parent": "Brendon Medugno",
    "email": "brendon.medugno@gmail.com",
    "phone": "602-790-1892",
    "age": 6,
    "city": "Windham",
    "sex": "M",
    "wr": "",
    "allergies": "",
    "tshirt": "YS",
    "notes": "",
    "weeks": "1,2,3,4,5,6,7,8",
    "weeks_arr": [
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1
    ],
    "reg_date": "",
    "special_notes": "",
    "is_emailed": false,
    "status": "enrolled"
  },
  {
    "id": 25,
    "name": "Brooklyn Kim",
    "ptft": "",
    "paid": "",
    "enrollment": "",
    "parent": "",
    "email": "",
    "phone": "",
    "age": 0,
    "city": "",
    "sex": "",
    "wr": "",
    "allergies": "",
    "tshirt": "",
    "notes": "",
    "weeks": "",
    "weeks_arr": [
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0
    ],
    "reg_date": "",
    "special_notes": "",
    "is_emailed": true,
    "status": "lead"
  },
  {
    "id": 26,
    "name": "Brynna Wasmer",
    "ptft": "FT",
    "paid": "yes",
    "enrollment": "yes",
    "parent": "Chris Wasmer",
    "email": "bluearrawana@hotmail.com",
    "phone": "9789300781",
    "age": 0,
    "city": "Haverhill",
    "sex": "F",
    "wr": "W & R",
    "allergies": "",
    "tshirt": "YM",
    "notes": "",
    "weeks": "1,2,3,4,5,6,7,8",
    "weeks_arr": [
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1
    ],
    "reg_date": "2026-01-28",
    "special_notes": "",
    "is_emailed": false,
    "status": "enrolled"
  },
  {
    "id": 27,
    "name": "Bryson Jonathas",
    "ptft": "",
    "paid": "",
    "enrollment": "",
    "parent": "",
    "email": "",
    "phone": "",
    "age": 0,
    "city": "",
    "sex": "",
    "wr": "",
    "allergies": "",
    "tshirt": "",
    "notes": "",
    "weeks": "",
    "weeks_arr": [
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0
    ],
    "reg_date": "",
    "special_notes": "",
    "is_emailed": true,
    "status": "lead"
  },
  {
    "id": 28,
    "name": "Caden O'Day",
    "ptft": "PT",
    "paid": "yes",
    "enrollment": "yes",
    "parent": "Lianne O'Day",
    "email": "lianne.oday@yahoo.com",
    "phone": "978-804-4364",
    "age": 11,
    "city": "Andover",
    "sex": "M",
    "wr": "W & R",
    "allergies": "red dye",
    "tshirt": "AS",
    "notes": "taking focalin for ADHD and prozac for anxiety",
    "weeks": "2,3,4,5,6",
    "weeks_arr": [
      0,
      1,
      1,
      1,
      1,
      1,
      0,
      0
    ],
    "reg_date": "2026-03-18",
    "special_notes": "",
    "is_emailed": false,
    "status": "enrolled"
  },
  {
    "id": 29,
    "name": "Caleb Robert",
    "ptft": "FT",
    "paid": "yes",
    "enrollment": "yes",
    "parent": "Ethan Robert",
    "email": "erobert1820@gmail.com",
    "phone": "802-733-4648",
    "age": 8,
    "city": "North Andover",
    "sex": "M",
    "wr": "W & R",
    "allergies": "",
    "tshirt": "YM",
    "notes": "",
    "weeks": "1,2,3,4,5,6,7,8",
    "weeks_arr": [
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1
    ],
    "reg_date": "2026-01-14",
    "special_notes": "",
    "is_emailed": false,
    "status": "enrolled"
  },
  {
    "id": 30,
    "name": "Calvin O'Day",
    "ptft": "PT",
    "paid": "yes",
    "enrollment": "yes",
    "parent": "Lianne O'Day",
    "email": "lianne.oday@yahoo.com",
    "phone": "978-804-4364",
    "age": 7,
    "city": "Andover",
    "sex": "M",
    "wr": "W & R",
    "allergies": "bandaid adhesive",
    "tshirt": "YL",
    "notes": "(use gauze + medical tape) instead of bandaids; mild asthma",
    "weeks": "5,6",
    "weeks_arr": [
      0,
      0,
      0,
      0,
      1,
      1,
      0,
      0
    ],
    "reg_date": "2026-03-18",
    "special_notes": "",
    "is_emailed": false,
    "status": "enrolled"
  },
  {
    "id": 31,
    "name": "Cameron Benoit",
    "ptft": "PT",
    "paid": "yes",
    "enrollment": "yes",
    "parent": "Amanda Benoit",
    "email": "amandagetchell2@gmail.com",
    "phone": "978-479-1108",
    "age": 8,
    "city": "Salem",
    "sex": "M",
    "wr": "W & R",
    "allergies": "environmental",
    "tshirt": "YM",
    "notes": "",
    "weeks": "1,3,6",
    "weeks_arr": [
      1,
      0,
      1,
      0,
      0,
      1,
      0,
      0
    ],
    "reg_date": "2026-02-03",
    "special_notes": "",
    "is_emailed": false,
    "status": "enrolled"
  },
  {
    "id": 32,
    "name": "Cameron O'Connell",
    "ptft": "PT",
    "paid": "yes",
    "enrollment": "no",
    "parent": "",
    "email": "",
    "phone": "",
    "age": 0,
    "city": "",
    "sex": "",
    "wr": "",
    "allergies": "",
    "tshirt": "",
    "notes": "",
    "weeks": "",
    "weeks_arr": [
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0
    ],
    "reg_date": "",
    "special_notes": "",
    "is_emailed": true,
    "status": "enrolled"
  },
  {
    "id": 33,
    "name": "Carleigh O'Brien",
    "ptft": "PT",
    "paid": "yes",
    "enrollment": "failed",
    "parent": "Melissa Atwood",
    "email": "matwood1985@gmail.com",
    "phone": "978-289-7882",
    "age": 8,
    "city": "North Andover",
    "sex": "F",
    "wr": "W & R",
    "allergies": "",
    "tshirt": "YM",
    "notes": "",
    "weeks": "1,8",
    "weeks_arr": [
      1,
      0,
      0,
      0,
      0,
      0,
      0,
      1
    ],
    "reg_date": "2026-01-19",
    "special_notes": "",
    "is_emailed": true,
    "status": "enrolled"
  },
  {
    "id": 34,
    "name": "Carter Curtis",
    "ptft": "PT",
    "paid": "yes",
    "enrollment": "yes",
    "parent": "Kristen Curtis",
    "email": "kristencurtis8613@gmail.com",
    "phone": "978-457-3705",
    "age": 10,
    "city": "Methuen",
    "sex": "M",
    "wr": "W & R",
    "allergies": "",
    "tshirt": "AM",
    "notes": "",
    "weeks": "1,2,4,5,6,7,8",
    "weeks_arr": [
      1,
      1,
      0,
      1,
      1,
      1,
      1,
      1
    ],
    "reg_date": "2026-01-17",
    "special_notes": "",
    "is_emailed": false,
    "status": "enrolled"
  },
  {
    "id": 35,
    "name": "Carter Johnson",
    "ptft": "PT",
    "paid": "yes",
    "enrollment": "yes",
    "parent": "Kara Johnson",
    "email": "knpillsbury@gmail.com",
    "phone": "978-771-5267",
    "age": 7,
    "city": "Haverhill",
    "sex": "M",
    "wr": "W & R",
    "allergies": "",
    "tshirt": "YM",
    "notes": "",
    "weeks": "3",
    "weeks_arr": [
      0,
      0,
      1,
      0,
      0,
      0,
      0,
      0
    ],
    "reg_date": "2026-02-08",
    "special_notes": "",
    "is_emailed": false,
    "status": "enrolled"
  },
  {
    "id": 36,
    "name": "Casey Guyotte",
    "ptft": "PT",
    "paid": "yes",
    "enrollment": "yes",
    "parent": "Stephanie Guyotte",
    "email": "scguyotte@gmail.com",
    "phone": "617-678-4094",
    "age": 10,
    "city": "Methuen",
    "sex": "M",
    "wr": "W & R",
    "allergies": "",
    "tshirt": "YM",
    "notes": "",
    "weeks": "3,4,6,7",
    "weeks_arr": [
      0,
      0,
      1,
      1,
      0,
      1,
      1,
      0
    ],
    "reg_date": "2026-03-16",
    "special_notes": "",
    "is_emailed": false,
    "status": "enrolled"
  },
  {
    "id": 37,
    "name": "Cayson Curtis",
    "ptft": "PT",
    "paid": "yes",
    "enrollment": "yes",
    "parent": "Kristen Curtis",
    "email": "kristencurtis8613@gmail.com",
    "phone": "978-457-3705",
    "age": 13,
    "city": "Methuen",
    "sex": "M",
    "wr": "W & R",
    "allergies": "",
    "tshirt": "AL",
    "notes": "",
    "weeks": "1,2,4,5,6,7,8",
    "weeks_arr": [
      1,
      1,
      0,
      1,
      1,
      1,
      1,
      1
    ],
    "reg_date": "2026-01-17",
    "special_notes": "",
    "is_emailed": false,
    "status": "enrolled"
  },
  {
    "id": 38,
    "name": "Charlotte Leon",
    "ptft": "PT",
    "paid": "yes",
    "enrollment": "no",
    "parent": "Paula Leon",
    "email": "pgagrabedian82@gmail.com",
    "phone": "603-548-9163",
    "age": 9,
    "city": "Salem",
    "sex": "F",
    "wr": "W & R",
    "allergies": "",
    "tshirt": "YL",
    "notes": "",
    "weeks": "1,3,5,7",
    "weeks_arr": [
      1,
      0,
      1,
      0,
      1,
      0,
      1,
      0
    ],
    "reg_date": "2026-01-30",
    "special_notes": "",
    "is_emailed": true,
    "status": "enrolled"
  },
  {
    "id": 39,
    "name": "Christian Kamolsiri",
    "ptft": "",
    "paid": "",
    "enrollment": "",
    "parent": "",
    "email": "",
    "phone": "",
    "age": 0,
    "city": "",
    "sex": "",
    "wr": "",
    "allergies": "",
    "tshirt": "",
    "notes": "",
    "weeks": "",
    "weeks_arr": [
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0
    ],
    "reg_date": "",
    "special_notes": "",
    "is_emailed": true,
    "status": "lead"
  },
  {
    "id": 40,
    "name": "Christopher Dardas",
    "ptft": "",
    "paid": "",
    "enrollment": "",
    "parent": "",
    "email": "",
    "phone": "",
    "age": 0,
    "city": "",
    "sex": "",
    "wr": "",
    "allergies": "",
    "tshirt": "",
    "notes": "",
    "weeks": "",
    "weeks_arr": [
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0
    ],
    "reg_date": "",
    "special_notes": "",
    "is_emailed": true,
    "status": "lead"
  },
  {
    "id": 41,
    "name": "Christoper (CJ) Fielding",
    "ptft": "PT",
    "paid": "yes",
    "enrollment": "yes",
    "parent": "Alan Fielding",
    "email": "al.fielding@gmail.com",
    "phone": "978-361-7206",
    "age": 10,
    "city": "Methuen",
    "sex": "M",
    "wr": "W & R",
    "allergies": "",
    "tshirt": "YM",
    "notes": "",
    "weeks": "1,2,3,5,6,7,8",
    "weeks_arr": [
      1,
      1,
      1,
      0,
      1,
      1,
      1,
      1
    ],
    "reg_date": "2026-02-05",
    "special_notes": "",
    "is_emailed": false,
    "status": "enrolled"
  },
  {
    "id": 42,
    "name": "Claire Petersen",
    "ptft": "PT",
    "paid": "yes",
    "enrollment": "yes",
    "parent": "Kelly Petersen",
    "email": "kelly.petersen07@gmail.com",
    "phone": "508-572-8400",
    "age": 9,
    "city": "Tewksbury",
    "sex": "F",
    "wr": "W & R",
    "allergies": "",
    "tshirt": "YM",
    "notes": "",
    "weeks": "1,2,5,6,8",
    "weeks_arr": [
      1,
      1,
      0,
      0,
      1,
      1,
      0,
      1
    ],
    "reg_date": "2026-01-22",
    "special_notes": "",
    "is_emailed": false,
    "status": "enrolled"
  },
  {
    "id": 43,
    "name": "Cole Arruda",
    "ptft": "PT",
    "paid": "yes",
    "enrollment": "",
    "parent": "Lisa Arruda",
    "email": "lisaamorim@yahoo.com",
    "phone": "617-438-7969",
    "age": 10,
    "city": "Salem",
    "sex": "M",
    "wr": "W & R",
    "allergies": "",
    "tshirt": "YXL",
    "notes": "",
    "weeks": "3,4,5,6,7,8",
    "weeks_arr": [
      0,
      0,
      1,
      1,
      1,
      1,
      1,
      1
    ],
    "reg_date": "2026-02-26",
    "special_notes": "",
    "is_emailed": true,
    "status": "enrolled"
  },
  {
    "id": 44,
    "name": "Cole Pitta",
    "ptft": "PT",
    "paid": "yes",
    "enrollment": "yes",
    "parent": "Ylan Pitta",
    "email": "ylan.pitta@gmail.com",
    "phone": "6036898901",
    "age": 8,
    "city": "Andover",
    "sex": "M",
    "wr": "W & R",
    "allergies": "",
    "tshirt": "YM",
    "notes": "",
    "weeks": "3",
    "weeks_arr": [
      0,
      0,
      1,
      0,
      0,
      0,
      0,
      0
    ],
    "reg_date": "2026-01-14",
    "special_notes": "",
    "is_emailed": false,
    "status": "enrolled"
  },
  {
    "id": 45,
    "name": "Cole Rivera",
    "ptft": "PT",
    "paid": "yes",
    "enrollment": "yes",
    "parent": "Jen Rivera",
    "email": "jennifer.morency@gmail.com",
    "phone": "978-609-4170",
    "age": 7,
    "city": "Haverhill",
    "sex": "M",
    "wr": "W & R",
    "allergies": "cherries,penicillin",
    "tshirt": "YS",
    "notes": "takes zyrtec as needed for hives",
    "weeks": "1,2,3,4,6",
    "weeks_arr": [
      1,
      1,
      1,
      1,
      0,
      1,
      0,
      0
    ],
    "reg_date": "2026-01-31",
    "special_notes": "",
    "is_emailed": false,
    "status": "enrolled"
  },
  {
    "id": 46,
    "name": "Colin Constant",
    "ptft": "",
    "paid": "",
    "enrollment": "",
    "parent": "",
    "email": "",
    "phone": "",
    "age": 0,
    "city": "",
    "sex": "",
    "wr": "",
    "allergies": "",
    "tshirt": "",
    "notes": "",
    "weeks": "",
    "weeks_arr": [
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0
    ],
    "reg_date": "",
    "special_notes": "",
    "is_emailed": true,
    "status": "lead"
  },
  {
    "id": 47,
    "name": "Colton Iworsky",
    "ptft": "PT",
    "paid": "yes",
    "enrollment": "yes",
    "parent": "Heather Iworsky",
    "email": "shortyheath@yahoo.com",
    "phone": "603-235-1267",
    "age": 6,
    "city": "Windham",
    "sex": "M",
    "wr": "W & R",
    "allergies": "pollen",
    "tshirt": "YM",
    "notes": "",
    "weeks": "2",
    "weeks_arr": [
      0,
      1,
      0,
      0,
      0,
      0,
      0,
      0
    ],
    "reg_date": "2026-01-15",
    "special_notes": "authorized pickup: Jen and Chris Plourde, Karen Iworsky, Doug and Katy Early",
    "is_emailed": false,
    "status": "enrolled"
  },
  {
    "id": 48,
    "name": "Cora Brashear",
    "ptft": "PT",
    "paid": "yes",
    "enrollment": "yes",
    "parent": "Jason Brashear",
    "email": "jay.brashear@yahoo.com",
    "phone": "508-873-4162",
    "age": 13,
    "city": "Melrose",
    "sex": "F",
    "wr": "W & R",
    "allergies": "",
    "tshirt": "AS",
    "notes": "",
    "weeks": "5,6",
    "weeks_arr": [
      0,
      0,
      0,
      0,
      1,
      1,
      0,
      0
    ],
    "reg_date": "2026-02-03",
    "special_notes": "",
    "is_emailed": false,
    "status": "enrolled"
  },
  {
    "id": 49,
    "name": "Corbin Gagne",
    "ptft": "PT",
    "paid": "yes",
    "enrollment": "yes",
    "parent": "Chris Gagne",
    "email": "chris.gagne30@gmail.com",
    "phone": "978-995-1659",
    "age": 9,
    "city": "Dracut",
    "sex": "M",
    "wr": "W & R",
    "allergies": "",
    "tshirt": "YL",
    "notes": "",
    "weeks": "3,4,5",
    "weeks_arr": [
      0,
      0,
      1,
      1,
      1,
      0,
      0,
      0
    ],
    "reg_date": "2026-03-05",
    "special_notes": "",
    "is_emailed": false,
    "status": "enrolled"
  },
  {
    "id": 50,
    "name": "Dale Gagne",
    "ptft": "PT",
    "paid": "yes",
    "enrollment": "yes",
    "parent": "Chris Gagne",
    "email": "chris.gagne30@gmail.com",
    "phone": "978-995-1659",
    "age": 7,
    "city": "Dracut",
    "sex": "M",
    "wr": "W & R",
    "allergies": "",
    "tshirt": "YM",
    "notes": "",
    "weeks": "3,4,5",
    "weeks_arr": [
      0,
      0,
      1,
      1,
      1,
      0,
      0,
      0
    ],
    "reg_date": "2026-03-05",
    "special_notes": "",
    "is_emailed": false,
    "status": "enrolled"
  },
  {
    "id": 51,
    "name": "Danielle Ruiz",
    "ptft": "PT",
    "paid": "yes",
    "enrollment": "yes",
    "parent": "Kristin Ruiz",
    "email": "kwright0586@gmail.com",
    "phone": "617-816-5482",
    "age": 0,
    "city": "Methuen",
    "sex": "F",
    "wr": "W & R",
    "allergies": "",
    "tshirt": "YM",
    "notes": "",
    "weeks": "5,8",
    "weeks_arr": [
      0,
      0,
      0,
      0,
      1,
      0,
      0,
      1
    ],
    "reg_date": "2026-01-30",
    "special_notes": "",
    "is_emailed": false,
    "status": "enrolled"
  },
  {
    "id": 52,
    "name": "Delaney Farrell",
    "ptft": "",
    "paid": "",
    "enrollment": "",
    "parent": "",
    "email": "",
    "phone": "",
    "age": 0,
    "city": "",
    "sex": "",
    "wr": "",
    "allergies": "",
    "tshirt": "",
    "notes": "",
    "weeks": "",
    "weeks_arr": [
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0
    ],
    "reg_date": "",
    "special_notes": "",
    "is_emailed": true,
    "status": "lead"
  },
  {
    "id": 53,
    "name": "Desmon Rondan",
    "ptft": "",
    "paid": "",
    "enrollment": "",
    "parent": "",
    "email": "",
    "phone": "",
    "age": 0,
    "city": "",
    "sex": "",
    "wr": "",
    "allergies": "",
    "tshirt": "",
    "notes": "",
    "weeks": "",
    "weeks_arr": [
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0
    ],
    "reg_date": "",
    "special_notes": "",
    "is_emailed": true,
    "status": "lead"
  },
  {
    "id": 54,
    "name": "Dominic Brashear",
    "ptft": "PT",
    "paid": "yes",
    "enrollment": "yes",
    "parent": "Jason Brashear",
    "email": "jay.brashear@yahoo.com",
    "phone": "508-873-4162",
    "age": 11,
    "city": "Melrose",
    "sex": "M",
    "wr": "W & R",
    "allergies": "",
    "tshirt": "YM",
    "notes": "",
    "weeks": "5,6",
    "weeks_arr": [
      0,
      0,
      0,
      0,
      1,
      1,
      0,
      0
    ],
    "reg_date": "2026-02-03",
    "special_notes": "",
    "is_emailed": false,
    "status": "enrolled"
  },
  {
    "id": 55,
    "name": "Donovan Powers",
    "ptft": "PT",
    "paid": "yes",
    "enrollment": "yes",
    "parent": "Alicia Powers",
    "email": "adp1980@comcast.net",
    "phone": "617-202-8085",
    "age": 10,
    "city": "Salem",
    "sex": "M",
    "wr": "W & R",
    "allergies": "",
    "tshirt": "YL",
    "notes": "",
    "weeks": "6,7",
    "weeks_arr": [
      0,
      0,
      0,
      0,
      0,
      1,
      1,
      0
    ],
    "reg_date": "2026-01-12",
    "special_notes": "",
    "is_emailed": false,
    "status": "enrolled"
  },
  {
    "id": 56,
    "name": "Dylan Mantha",
    "ptft": "PT",
    "paid": "yes",
    "enrollment": "yes",
    "parent": "Chinghui Mantha",
    "email": "norika0821@hotmail.com",
    "phone": "603-264-9136",
    "age": 8,
    "city": "Andover",
    "sex": "M",
    "wr": "W & R",
    "allergies": "",
    "tshirt": "YL",
    "notes": "",
    "weeks": "5",
    "weeks_arr": [
      0,
      0,
      0,
      0,
      1,
      0,
      0,
      0
    ],
    "reg_date": "2026-01-30",
    "special_notes": "",
    "is_emailed": false,
    "status": "enrolled"
  },
  {
    "id": 57,
    "name": "Eason Wasmer",
    "ptft": "FT",
    "paid": "yes",
    "enrollment": "yes",
    "parent": "Chris Wasmer",
    "email": "bluearrawana@hotmail.com",
    "phone": "9789300781",
    "age": 0,
    "city": "Haverhill",
    "sex": "M",
    "wr": "W & R",
    "allergies": "",
    "tshirt": "AS",
    "notes": "",
    "weeks": "1,2,3,4,5,6,7,8",
    "weeks_arr": [
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1
    ],
    "reg_date": "2026-01-28",
    "special_notes": "",
    "is_emailed": false,
    "status": "enrolled"
  },
  {
    "id": 58,
    "name": "Edward Constant",
    "ptft": "",
    "paid": "",
    "enrollment": "",
    "parent": "",
    "email": "",
    "phone": "",
    "age": 0,
    "city": "",
    "sex": "",
    "wr": "",
    "allergies": "",
    "tshirt": "",
    "notes": "",
    "weeks": "",
    "weeks_arr": [
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0
    ],
    "reg_date": "",
    "special_notes": "",
    "is_emailed": true,
    "status": "lead"
  },
  {
    "id": 59,
    "name": "Ella Brien",
    "ptft": "PT",
    "paid": "yes",
    "enrollment": "yes",
    "parent": "Kate Brien",
    "email": "kathleenbrien29@gmail.com",
    "phone": "978-314-2730",
    "age": 6,
    "city": "North Andover",
    "sex": "F",
    "wr": "W & R",
    "allergies": "",
    "tshirt": "YS",
    "notes": "",
    "weeks": "1,2,3,4,6",
    "weeks_arr": [
      1,
      1,
      1,
      1,
      0,
      1,
      0,
      0
    ],
    "reg_date": "2026-01-07",
    "special_notes": "",
    "is_emailed": false,
    "status": "enrolled"
  },
  {
    "id": 60,
    "name": "Emerson Greenleaf",
    "ptft": "PT",
    "paid": "yes",
    "enrollment": "yes",
    "parent": "Kaitlyn Greenleaf",
    "email": "kgreenleaf2@gmail.com",
    "phone": "978-987-0657",
    "age": 5,
    "city": "Windham",
    "sex": "F",
    "wr": "W & R",
    "allergies": "",
    "tshirt": "YM",
    "notes": "",
    "weeks": "8",
    "weeks_arr": [
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      1
    ],
    "reg_date": "2026-02-04",
    "special_notes": "",
    "is_emailed": false,
    "status": "enrolled"
  },
  {
    "id": 61,
    "name": "Esmeralda Guzman",
    "ptft": "",
    "paid": "",
    "enrollment": "",
    "parent": "",
    "email": "",
    "phone": "",
    "age": 0,
    "city": "",
    "sex": "",
    "wr": "",
    "allergies": "",
    "tshirt": "",
    "notes": "",
    "weeks": "",
    "weeks_arr": [
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0
    ],
    "reg_date": "",
    "special_notes": "",
    "is_emailed": false,
    "status": "lead"
  },
  {
    "id": 62,
    "name": "Ethan Chetson",
    "ptft": "PT",
    "paid": "yes",
    "enrollment": "yes",
    "parent": "Amanda Chetson",
    "email": "arotando1@gmail.com",
    "phone": "978-204-5113",
    "age": 6,
    "city": "Methuen",
    "sex": "M",
    "wr": "W & R",
    "allergies": "",
    "tshirt": "YS",
    "notes": "",
    "weeks": "3,4,5,6,7,8",
    "weeks_arr": [
      0,
      0,
      1,
      1,
      1,
      1,
      1,
      1
    ],
    "reg_date": "2026-03-13",
    "special_notes": "",
    "is_emailed": false,
    "status": "enrolled"
  },
  {
    "id": 63,
    "name": "Ethan Costello",
    "ptft": "FT",
    "paid": "yes",
    "enrollment": "",
    "parent": "Katie Costello",
    "email": "katie_as_is@hotmail.com",
    "phone": "978-518-0771",
    "age": 6,
    "city": "Hampstead",
    "sex": "M",
    "wr": "W & R",
    "allergies": "",
    "tshirt": "YS",
    "notes": "",
    "weeks": "1,2,3,4,5,6,7,8",
    "weeks_arr": [
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1
    ],
    "reg_date": "2026-04-02",
    "special_notes": "",
    "is_emailed": true,
    "status": "enrolled"
  },
  {
    "id": 64,
    "name": "Finnegan Nolan",
    "ptft": "",
    "paid": "",
    "enrollment": "",
    "parent": "",
    "email": "",
    "phone": "",
    "age": 0,
    "city": "",
    "sex": "",
    "wr": "",
    "allergies": "",
    "tshirt": "",
    "notes": "",
    "weeks": "",
    "weeks_arr": [
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0
    ],
    "reg_date": "",
    "special_notes": "",
    "is_emailed": true,
    "status": "lead"
  },
  {
    "id": 65,
    "name": "Gabriel Nunez",
    "ptft": "PT",
    "paid": "yes",
    "enrollment": "failed",
    "parent": "Angela Nunez",
    "email": "acatizone14@hotmail.com",
    "phone": "781-771-5028",
    "age": 8,
    "city": "Methuen",
    "sex": "M",
    "wr": "W & R",
    "allergies": "amoxicillin",
    "tshirt": "YL",
    "notes": "",
    "weeks": "1,2,3,4,5,6,7,8",
    "weeks_arr": [
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1
    ],
    "reg_date": "2026-02-04",
    "special_notes": "",
    "is_emailed": true,
    "status": "enrolled"
  },
  {
    "id": 66,
    "name": "Gabriella Dowd",
    "ptft": "",
    "paid": "no",
    "enrollment": "no",
    "parent": "",
    "email": "",
    "phone": "",
    "age": 0,
    "city": "",
    "sex": "",
    "wr": "",
    "allergies": "",
    "tshirt": "",
    "notes": "",
    "weeks": "",
    "weeks_arr": [
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0
    ],
    "reg_date": "",
    "special_notes": "",
    "is_emailed": false,
    "status": "lead"
  },
  {
    "id": 67,
    "name": "Gabriella Ingersoll",
    "ptft": "PT",
    "paid": "yes",
    "enrollment": "yes",
    "parent": "Emily Ingersoll",
    "email": "emilykate87@yahoo.com",
    "phone": "617-680-1960",
    "age": 9,
    "city": "North Andover",
    "sex": "F",
    "wr": "W & R",
    "allergies": "",
    "tshirt": "YM",
    "notes": "",
    "weeks": "2,3,4,5,8",
    "weeks_arr": [
      0,
      1,
      1,
      1,
      1,
      0,
      0,
      1
    ],
    "reg_date": "2026-01-17",
    "special_notes": "",
    "is_emailed": false,
    "status": "enrolled"
  },
  {
    "id": 68,
    "name": "Gannon Nicolosi",
    "ptft": "",
    "paid": "",
    "enrollment": "",
    "parent": "",
    "email": "",
    "phone": "",
    "age": 0,
    "city": "",
    "sex": "",
    "wr": "",
    "allergies": "",
    "tshirt": "",
    "notes": "",
    "weeks": "",
    "weeks_arr": [
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0
    ],
    "reg_date": "",
    "special_notes": "",
    "is_emailed": true,
    "status": "lead"
  },
  {
    "id": 69,
    "name": "Gavin Kelloway",
    "ptft": "",
    "paid": "",
    "enrollment": "",
    "parent": "",
    "email": "",
    "phone": "",
    "age": 0,
    "city": "",
    "sex": "",
    "wr": "",
    "allergies": "",
    "tshirt": "",
    "notes": "",
    "weeks": "",
    "weeks_arr": [
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0
    ],
    "reg_date": "",
    "special_notes": "",
    "is_emailed": true,
    "status": "lead"
  },
  {
    "id": 70,
    "name": "George Koskores",
    "ptft": "PT",
    "paid": "yes",
    "enrollment": "yes",
    "parent": "Alex Koskores",
    "email": "akoskores@gmail.com",
    "phone": "508-446-0989",
    "age": 6,
    "city": "North Andover",
    "sex": "M",
    "wr": "W & R",
    "allergies": "",
    "tshirt": "YS",
    "notes": "",
    "weeks": "1,2,4,5,6",
    "weeks_arr": [
      1,
      1,
      0,
      1,
      1,
      1,
      0,
      0
    ],
    "reg_date": "2026-01-06",
    "special_notes": "",
    "is_emailed": false,
    "status": "enrolled"
  },
  {
    "id": 71,
    "name": "Giovanna (Gigi) Pajazetovic",
    "ptft": "PT",
    "paid": "yes",
    "enrollment": "no",
    "parent": "Giselle Pajazetovic",
    "email": "gigireoli@hotmail.com",
    "phone": "617-501-8512",
    "age": 0,
    "city": "North Andover",
    "sex": "F",
    "wr": "W & R",
    "allergies": "",
    "tshirt": "YL",
    "notes": "",
    "weeks": "2,3,4,5,6,7,8",
    "weeks_arr": [
      0,
      1,
      1,
      1,
      1,
      1,
      1,
      1
    ],
    "reg_date": "2026-01-26",
    "special_notes": "",
    "is_emailed": true,
    "status": "enrolled"
  },
  {
    "id": 72,
    "name": "Grace Ingersoll",
    "ptft": "PT",
    "paid": "yes",
    "enrollment": "yes",
    "parent": "Emily Ingersoll",
    "email": "emilykate87@yahoo.com",
    "phone": "617-680-1960",
    "age": 0,
    "city": "North Andover",
    "sex": "F",
    "wr": "W & R",
    "allergies": "cashews, pistachios",
    "tshirt": "YM",
    "notes": "",
    "weeks": "2,3,4,5,8",
    "weeks_arr": [
      0,
      1,
      1,
      1,
      1,
      0,
      0,
      1
    ],
    "reg_date": "2026-01-17",
    "special_notes": "",
    "is_emailed": false,
    "status": "enrolled"
  },
  {
    "id": 73,
    "name": "Greyson O'Connor",
    "ptft": "FT",
    "paid": "yes",
    "enrollment": "yes",
    "parent": "Cody O'Connor",
    "email": "codyoconnor916@gmail.com",
    "phone": "978-273-5720",
    "age": 7,
    "city": "Methuen",
    "sex": "M",
    "wr": "W & R",
    "allergies": "",
    "tshirt": "YS",
    "notes": "",
    "weeks": "1,2,3,4,5,6,7,8",
    "weeks_arr": [
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1
    ],
    "reg_date": "2026-01-30",
    "special_notes": "",
    "is_emailed": false,
    "status": "enrolled"
  },
  {
    "id": 74,
    "name": "Henry Cyr",
    "ptft": "",
    "paid": "",
    "enrollment": "",
    "parent": "",
    "email": "",
    "phone": "",
    "age": 0,
    "city": "",
    "sex": "",
    "wr": "",
    "allergies": "",
    "tshirt": "",
    "notes": "",
    "weeks": "",
    "weeks_arr": [
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0
    ],
    "reg_date": "",
    "special_notes": "",
    "is_emailed": true,
    "status": "lead"
  },
  {
    "id": 75,
    "name": "Henry Hubert",
    "ptft": "PT",
    "paid": "yes",
    "enrollment": "yes",
    "parent": "Jessica Hubert",
    "email": "jess.n.hubert@gmail.com",
    "phone": "603-508-8005",
    "age": 7,
    "city": "Haverhill",
    "sex": "M",
    "wr": "W & R",
    "allergies": "",
    "tshirt": "YS",
    "notes": "",
    "weeks": "3,4,5,6,7",
    "weeks_arr": [
      0,
      0,
      1,
      1,
      1,
      1,
      1,
      0
    ],
    "reg_date": "2026-01-25",
    "special_notes": "",
    "is_emailed": false,
    "status": "enrolled"
  },
  {
    "id": 76,
    "name": "Hugo Frederick",
    "ptft": "PT",
    "paid": "yes",
    "enrollment": "yes",
    "parent": "",
    "email": "",
    "phone": "",
    "age": 0,
    "city": "",
    "sex": "",
    "wr": "",
    "allergies": "",
    "tshirt": "",
    "notes": "",
    "weeks": "6,7",
    "weeks_arr": [
      0,
      0,
      0,
      0,
      0,
      1,
      1,
      0
    ],
    "reg_date": "2026-01-16",
    "special_notes": "",
    "is_emailed": true,
    "status": "enrolled"
  },
  {
    "id": 77,
    "name": "Isaac Marani",
    "ptft": "PT",
    "paid": "yes",
    "enrollment": "no",
    "parent": "Heidi Marani",
    "email": "bostonheidi1@aol.com",
    "phone": "617-947-7660",
    "age": 8,
    "city": "Andover",
    "sex": "M",
    "wr": "W & R",
    "allergies": "apples",
    "tshirt": "YS",
    "notes": "",
    "weeks": "3",
    "weeks_arr": [
      0,
      0,
      1,
      0,
      0,
      0,
      0,
      0
    ],
    "reg_date": "2026-01-15",
    "special_notes": "",
    "is_emailed": true,
    "status": "enrolled"
  },
  {
    "id": 78,
    "name": "Isabella Vasconcellos",
    "ptft": "PT",
    "paid": "yes",
    "enrollment": "no",
    "parent": "Michael Vasconcellos",
    "email": "vasconcellos25@gmail.com",
    "phone": "978-804-2130",
    "age": 11,
    "city": "Methuen",
    "sex": "F",
    "wr": "W & R",
    "allergies": "",
    "tshirt": "YM",
    "notes": "",
    "weeks": "7",
    "weeks_arr": [
      0,
      0,
      0,
      0,
      0,
      0,
      1,
      0
    ],
    "reg_date": "2026-01-29",
    "special_notes": "",
    "is_emailed": true,
    "status": "enrolled"
  },
  {
    "id": 79,
    "name": "Isabella Vasquez",
    "ptft": "PT",
    "paid": "yes",
    "enrollment": "yes",
    "parent": "Maderlyn Vasquez",
    "email": "maderlynvasquez95@gmail.com",
    "phone": "978-852-5372",
    "age": 5,
    "city": "Lawrence",
    "sex": "F",
    "wr": "R",
    "allergies": "",
    "tshirt": "YM",
    "notes": "",
    "weeks": "4,5",
    "weeks_arr": [
      0,
      0,
      0,
      1,
      1,
      0,
      0,
      0
    ],
    "reg_date": "2026-03-16",
    "special_notes": "",
    "is_emailed": true,
    "status": "enrolled"
  },
  {
    "id": 80,
    "name": "Isabelle Kennedy",
    "ptft": "PT",
    "paid": "yes",
    "enrollment": "yes",
    "parent": "Lorraine Kennedy",
    "email": "leforan16@gmail.com",
    "phone": "339-221-4823",
    "age": 0,
    "city": "Methuen",
    "sex": "F",
    "wr": "W & R",
    "allergies": "",
    "tshirt": "YM",
    "notes": "",
    "weeks": "2,5,8",
    "weeks_arr": [
      0,
      1,
      0,
      0,
      1,
      0,
      0,
      1
    ],
    "reg_date": "2026-01-28",
    "special_notes": "",
    "is_emailed": false,
    "status": "enrolled"
  },
  {
    "id": 81,
    "name": "Jack Connolly",
    "ptft": "PT",
    "paid": "yes",
    "enrollment": "yes",
    "parent": "Michelle Connolly",
    "email": "mhoward411@gmail.com",
    "phone": "978-994-3945",
    "age": 7,
    "city": "North Andover",
    "sex": "M",
    "wr": "W & R",
    "allergies": "",
    "tshirt": "YM",
    "notes": "",
    "weeks": "2",
    "weeks_arr": [
      0,
      1,
      0,
      0,
      0,
      0,
      0,
      0
    ],
    "reg_date": "2026-03-19",
    "special_notes": "",
    "is_emailed": false,
    "status": "enrolled"
  },
  {
    "id": 82,
    "name": "Jacob Parkes",
    "ptft": "FT",
    "paid": "yes",
    "enrollment": "yes",
    "parent": "Krystle Parkes",
    "email": "kparkes531@gmail.com",
    "phone": "978-979-4502",
    "age": 6,
    "city": "Haverhill",
    "sex": "M",
    "wr": "W & R",
    "allergies": "",
    "tshirt": "YM",
    "notes": "",
    "weeks": "1,2,3,4,5,6,7,8",
    "weeks_arr": [
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1
    ],
    "reg_date": "2026-01-09",
    "special_notes": "",
    "is_emailed": false,
    "status": "enrolled"
  },
  {
    "id": 83,
    "name": "James Durkin",
    "ptft": "PT",
    "paid": "yes",
    "enrollment": "yes",
    "parent": "Stephanie Durkin",
    "email": "sgiuca8613@yahoo.com",
    "phone": "",
    "age": 11,
    "city": "Methuen",
    "sex": "M",
    "wr": "W & R",
    "allergies": "dogs, cats, birch",
    "tshirt": "YM",
    "notes": "",
    "weeks": "3,4,5,6,8",
    "weeks_arr": [
      0,
      0,
      1,
      1,
      1,
      1,
      0,
      1
    ],
    "reg_date": "2026-01-29",
    "special_notes": "",
    "is_emailed": false,
    "status": "enrolled"
  },
  {
    "id": 84,
    "name": "Jaxon Iworsky",
    "ptft": "PT",
    "paid": "yes",
    "enrollment": "yes",
    "parent": "Heather Iworsky",
    "email": "shortyheath@yahoo.com",
    "phone": "603-235-1267",
    "age": 7,
    "city": "Windham",
    "sex": "M",
    "wr": "W & R",
    "allergies": "pollen",
    "tshirt": "YM",
    "notes": "",
    "weeks": "2",
    "weeks_arr": [
      0,
      1,
      0,
      0,
      0,
      0,
      0,
      0
    ],
    "reg_date": "2026-01-15",
    "special_notes": "authorized pickup: Jen and Chris Plourde, Karen Iworsky, Doug and Katy Early",
    "is_emailed": false,
    "status": "enrolled"
  },
  {
    "id": 85,
    "name": "Jaxxon Tyler",
    "ptft": "PT",
    "paid": "yes",
    "enrollment": "no",
    "parent": "Cyndie Fortier",
    "email": "cyndiefortier@yahoo.com",
    "phone": "603-339-6366",
    "age": 0,
    "city": "Methuen",
    "sex": "M",
    "wr": "R",
    "allergies": "seasonal allergy",
    "tshirt": "YM",
    "notes": "",
    "weeks": "1,2,3,4,5,6,7",
    "weeks_arr": [
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      0
    ],
    "reg_date": "2026-01-20",
    "special_notes": "",
    "is_emailed": true,
    "status": "enrolled"
  },
  {
    "id": 86,
    "name": "Joelle Hubert",
    "ptft": "PT",
    "paid": "yes",
    "enrollment": "yes",
    "parent": "Jessica Hubert",
    "email": "jess.n.hubert@gmail.com",
    "phone": "603-508-8005",
    "age": 9,
    "city": "Haverhill",
    "sex": "F",
    "wr": "W & R",
    "allergies": "",
    "tshirt": "YM",
    "notes": "",
    "weeks": "3,4,5,6,7",
    "weeks_arr": [
      0,
      0,
      1,
      1,
      1,
      1,
      1,
      0
    ],
    "reg_date": "2026-01-25",
    "special_notes": "",
    "is_emailed": false,
    "status": "enrolled"
  },
  {
    "id": 87,
    "name": "John Roberts",
    "ptft": "PT",
    "paid": "yes",
    "enrollment": "yes",
    "parent": "Constance Roberts",
    "email": "conniemf82@gmail.com",
    "phone": "978-360-9602",
    "age": 7,
    "city": "Salem",
    "sex": "M",
    "wr": "W & R",
    "allergies": "",
    "tshirt": "YM",
    "notes": "",
    "weeks": "1,2,3,4,5,6,8",
    "weeks_arr": [
      1,
      1,
      1,
      1,
      1,
      1,
      0,
      1
    ],
    "reg_date": "2026-01-28",
    "special_notes": "",
    "is_emailed": false,
    "status": "enrolled"
  },
  {
    "id": 88,
    "name": "Jorgelys Vasquez",
    "ptft": "PT",
    "paid": "yes",
    "enrollment": "yes",
    "parent": "Maderlyn Vasquez",
    "email": "maderlynvasquez95@gmail.com",
    "phone": "978-852-5372",
    "age": 10,
    "city": "Lawrence",
    "sex": "F",
    "wr": "R",
    "allergies": "",
    "tshirt": "YL",
    "notes": "",
    "weeks": "4,5",
    "weeks_arr": [
      0,
      0,
      0,
      1,
      1,
      0,
      0,
      0
    ],
    "reg_date": "2026-03-16",
    "special_notes": "",
    "is_emailed": true,
    "status": "enrolled"
  },
  {
    "id": 89,
    "name": "Joseph Marino",
    "ptft": "FT",
    "paid": "yes",
    "enrollment": "yes",
    "parent": "Stephanie Marino",
    "email": "smarino1820@gmail.com",
    "phone": "978-376-4517",
    "age": 7,
    "city": "North Andover",
    "sex": "M",
    "wr": "W & R",
    "allergies": "environmental",
    "tshirt": "YS",
    "notes": "",
    "weeks": "1,2,3,4,5,6,7,8",
    "weeks_arr": [
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1
    ],
    "reg_date": "2026-01-14",
    "special_notes": "",
    "is_emailed": false,
    "status": "enrolled"
  },
  {
    "id": 90,
    "name": "Joseph Roberts",
    "ptft": "PT",
    "paid": "yes",
    "enrollment": "yes",
    "parent": "Constance Roberts",
    "email": "conniemf82@gmail.com",
    "phone": "978-360-9602",
    "age": 8,
    "city": "Salem",
    "sex": "M",
    "wr": "W & R",
    "allergies": "",
    "tshirt": "YM",
    "notes": "",
    "weeks": "1,2,3,4,5,6,8",
    "weeks_arr": [
      1,
      1,
      1,
      1,
      1,
      1,
      0,
      1
    ],
    "reg_date": "2026-01-28",
    "special_notes": "",
    "is_emailed": false,
    "status": "enrolled"
  },
  {
    "id": 91,
    "name": "Joshua Guzman",
    "ptft": "",
    "paid": "",
    "enrollment": "",
    "parent": "",
    "email": "",
    "phone": "",
    "age": 0,
    "city": "",
    "sex": "",
    "wr": "",
    "allergies": "",
    "tshirt": "",
    "notes": "",
    "weeks": "",
    "weeks_arr": [
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0
    ],
    "reg_date": "",
    "special_notes": "",
    "is_emailed": false,
    "status": "lead"
  },
  {
    "id": 92,
    "name": "Keegan Slein",
    "ptft": "",
    "paid": "",
    "enrollment": "",
    "parent": "",
    "email": "",
    "phone": "",
    "age": 0,
    "city": "",
    "sex": "",
    "wr": "",
    "allergies": "",
    "tshirt": "",
    "notes": "",
    "weeks": "",
    "weeks_arr": [
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0
    ],
    "reg_date": "",
    "special_notes": "",
    "is_emailed": true,
    "status": "lead"
  },
  {
    "id": 93,
    "name": "Keira Spaulding",
    "ptft": "PT",
    "paid": "yes",
    "enrollment": "yes",
    "parent": "Danielle Spaulding",
    "email": "danielle.spaulding322@gmail.com",
    "phone": "978-684-2191",
    "age": 0,
    "city": "Tewksbury",
    "sex": "F",
    "wr": "W & R",
    "allergies": "peanuts",
    "tshirt": "YL",
    "notes": "takes ADHD meds",
    "weeks": "1,2,5,6,8",
    "weeks_arr": [
      1,
      1,
      0,
      0,
      1,
      1,
      0,
      1
    ],
    "reg_date": "2026-01-23",
    "special_notes": "",
    "is_emailed": false,
    "status": "enrolled"
  },
  {
    "id": 94,
    "name": "Kelan Fuoco",
    "ptft": "PT",
    "paid": "yes",
    "enrollment": "yes",
    "parent": "Ida Fuoco",
    "email": "idamfuoco@gmail.com",
    "phone": "978-420-6043",
    "age": 11,
    "city": "Salem",
    "sex": "M",
    "wr": "W & R",
    "allergies": "",
    "tshirt": "YL",
    "notes": "",
    "weeks": "1,2,3,4,5,6",
    "weeks_arr": [
      1,
      1,
      1,
      1,
      1,
      1,
      0,
      0
    ],
    "reg_date": "2026-02-07",
    "special_notes": "",
    "is_emailed": false,
    "status": "enrolled"
  },
  {
    "id": 95,
    "name": "Landon Creamer",
    "ptft": "PT",
    "paid": "yes",
    "enrollment": "yes",
    "parent": "Brianne Creamer",
    "email": "brianne.creamer@hotmail.com",
    "phone": "603-674-4218",
    "age": 13,
    "city": "Salem",
    "sex": "M",
    "wr": "W & R",
    "allergies": "",
    "tshirt": "YL",
    "notes": "",
    "weeks": "1,2,3,4,6,7",
    "weeks_arr": [
      1,
      1,
      1,
      1,
      0,
      1,
      1,
      0
    ],
    "reg_date": "2026-01-17",
    "special_notes": "",
    "is_emailed": false,
    "status": "enrolled"
  },
  {
    "id": 96,
    "name": "Landon Hynes",
    "ptft": "FT",
    "paid": "yes",
    "enrollment": "yes",
    "parent": "",
    "email": "",
    "phone": "",
    "age": 0,
    "city": "",
    "sex": "M",
    "wr": "",
    "allergies": "",
    "tshirt": "",
    "notes": "",
    "weeks": "",
    "weeks_arr": [
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0
    ],
    "reg_date": "",
    "special_notes": "",
    "is_emailed": true,
    "status": "enrolled"
  },
  {
    "id": 97,
    "name": "Leonardo Maria",
    "ptft": "FT",
    "paid": "yes",
    "enrollment": "yes",
    "parent": "Diana Maria",
    "email": "diana.castillo927@gmail.com",
    "phone": "856-756-5056",
    "age": 9,
    "city": "Lawrence",
    "sex": "M",
    "wr": "W & R",
    "allergies": "",
    "tshirt": "YL",
    "notes": "adderall",
    "weeks": "1,2,3,4,5,6,7,8",
    "weeks_arr": [
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1
    ],
    "reg_date": "2026-03-31",
    "special_notes": "",
    "is_emailed": false,
    "status": "enrolled"
  },
  {
    "id": 98,
    "name": "Leo Oullette",
    "ptft": "",
    "paid": "",
    "enrollment": "",
    "parent": "",
    "email": "",
    "phone": "",
    "age": 0,
    "city": "",
    "sex": "",
    "wr": "",
    "allergies": "",
    "tshirt": "",
    "notes": "",
    "weeks": "",
    "weeks_arr": [
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0
    ],
    "reg_date": "",
    "special_notes": "",
    "is_emailed": true,
    "status": "lead"
  },
  {
    "id": 99,
    "name": "Liam Nolan",
    "ptft": "",
    "paid": "",
    "enrollment": "",
    "parent": "",
    "email": "",
    "phone": "",
    "age": 0,
    "city": "",
    "sex": "",
    "wr": "",
    "allergies": "",
    "tshirt": "",
    "notes": "",
    "weeks": "",
    "weeks_arr": [
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0
    ],
    "reg_date": "",
    "special_notes": "",
    "is_emailed": true,
    "status": "lead"
  },
  {
    "id": 100,
    "name": "Liam Phair",
    "ptft": "PT",
    "paid": "yes",
    "enrollment": "yes",
    "parent": "Shayna Robinson",
    "email": "shaylm226@gmail.com",
    "phone": "978-807-5280",
    "age": 10,
    "city": "Dracut",
    "sex": "M",
    "wr": "W & R",
    "allergies": "",
    "tshirt": "YL",
    "notes": "takes guanfacine and clonidine for ADHD",
    "weeks": "1,3,5,7",
    "weeks_arr": [
      1,
      0,
      1,
      0,
      1,
      0,
      1,
      0
    ],
    "reg_date": "2026-02-15",
    "special_notes": "",
    "is_emailed": false,
    "status": "enrolled"
  },
  {
    "id": 101,
    "name": "Liam Pintzopoulos",
    "ptft": "PT",
    "paid": "yes",
    "enrollment": "yes",
    "parent": "Dino Pintzopoulos",
    "email": "minion450@gmail.com",
    "phone": "978-771-9205",
    "age": 11,
    "city": "Hampstead",
    "sex": "M",
    "wr": "W & R",
    "allergies": "",
    "tshirt": "AS",
    "notes": "takes guanfacine for ADHD; level 1 autistic",
    "weeks": "1,2,3,5,6,7,8",
    "weeks_arr": [
      1,
      1,
      1,
      0,
      1,
      1,
      1,
      1
    ],
    "reg_date": "2026-02-04",
    "special_notes": "",
    "is_emailed": false,
    "status": "enrolled"
  },
  {
    "id": 102,
    "name": "Lincoln Affronti",
    "ptft": "PT",
    "paid": "yes",
    "enrollment": "yes",
    "parent": "Heidi Affronti",
    "email": "heidi.affronti@gmail.com",
    "phone": "207-522-4132",
    "age": 7,
    "city": "Salem",
    "sex": "M",
    "wr": "W & R",
    "allergies": "",
    "tshirt": "YS",
    "notes": "",
    "weeks": "3,6",
    "weeks_arr": [
      0,
      0,
      1,
      0,
      0,
      1,
      0,
      0
    ],
    "reg_date": "2026-01-24",
    "special_notes": "",
    "is_emailed": false,
    "status": "enrolled"
  },
  {
    "id": 103,
    "name": "Logan Martins",
    "ptft": "PT",
    "paid": "yes",
    "enrollment": "yes",
    "parent": "Amy Martins",
    "email": "amy.n.martins@gmail.com",
    "phone": "603-560-0023",
    "age": 10,
    "city": "Windham",
    "sex": "M",
    "wr": "W & R",
    "allergies": "",
    "tshirt": "YXL",
    "notes": "",
    "weeks": "3,4,?",
    "weeks_arr": [
      0,
      0,
      1,
      0,
      0,
      1,
      0,
      0
    ],
    "reg_date": "2026-01-27",
    "special_notes": "",
    "is_emailed": false,
    "status": "enrolled"
  },
  {
    "id": 104,
    "name": "Lorenzo Maria",
    "ptft": "FT",
    "paid": "yes",
    "enrollment": "yes",
    "parent": "Diana Maria",
    "email": "diana.castillo927@gmail.com",
    "phone": "857-756-5056",
    "age": 6,
    "city": "Lawrence",
    "sex": "M",
    "wr": "W & R",
    "allergies": "pet fur, dogs, cats",
    "tshirt": "YM",
    "notes": "claritan",
    "weeks": "1,2,3,4,5,6,7,8",
    "weeks_arr": [
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1
    ],
    "reg_date": "2026-03-31",
    "special_notes": "",
    "is_emailed": false,
    "status": "enrolled"
  },
  {
    "id": 105,
    "name": "Luna Mia Vargas",
    "ptft": "FT",
    "paid": "no",
    "enrollment": "no",
    "parent": "Rubi Vargas",
    "email": "rubivargasx25@gmail.com",
    "phone": "978-284-3781",
    "age": 5,
    "city": "Lawrence",
    "sex": "F",
    "wr": "W & R",
    "allergies": "",
    "tshirt": "YXS",
    "notes": "albuterol inhaler as needed",
    "weeks": "1,2,3,4,5,6,7,8",
    "weeks_arr": [
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1
    ],
    "reg_date": "",
    "special_notes": "",
    "is_emailed": true,
    "status": "enrolled"
  },
  {
    "id": 106,
    "name": "Maeve Farrell",
    "ptft": "",
    "paid": "",
    "enrollment": "",
    "parent": "",
    "email": "",
    "phone": "",
    "age": 0,
    "city": "",
    "sex": "",
    "wr": "",
    "allergies": "",
    "tshirt": "",
    "notes": "",
    "weeks": "",
    "weeks_arr": [
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0
    ],
    "reg_date": "",
    "special_notes": "",
    "is_emailed": true,
    "status": "lead"
  },
  {
    "id": 107,
    "name": "Makenna Douglass",
    "ptft": "",
    "paid": "",
    "enrollment": "",
    "parent": "",
    "email": "",
    "phone": "",
    "age": 0,
    "city": "",
    "sex": "",
    "wr": "",
    "allergies": "",
    "tshirt": "",
    "notes": "",
    "weeks": "",
    "weeks_arr": [
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0
    ],
    "reg_date": "",
    "special_notes": "",
    "is_emailed": true,
    "status": "lead"
  },
  {
    "id": 108,
    "name": "Margaret Early",
    "ptft": "PT",
    "paid": "yes",
    "enrollment": "yes",
    "parent": "Kathryn Early",
    "email": "katymearly@gmail.com",
    "phone": "978-257-7683",
    "age": 6,
    "city": "Atkinson",
    "sex": "F",
    "wr": "W & R",
    "allergies": "",
    "tshirt": "YM",
    "notes": "",
    "weeks": "2",
    "weeks_arr": [
      0,
      1,
      0,
      0,
      0,
      0,
      0,
      0
    ],
    "reg_date": "2026-01-06",
    "special_notes": "",
    "is_emailed": false,
    "status": "enrolled"
  },
  {
    "id": 109,
    "name": "Marissa Phair",
    "ptft": "PT",
    "paid": "yes",
    "enrollment": "yes",
    "parent": "Shayna Robinson",
    "email": "shaylm226@gmail.com",
    "phone": "978-807-5280",
    "age": 5,
    "city": "Dracut",
    "sex": "F",
    "wr": "W & R",
    "allergies": "",
    "tshirt": "YM",
    "notes": "",
    "weeks": "1,3,5,7",
    "weeks_arr": [
      1,
      0,
      1,
      0,
      1,
      0,
      1,
      0
    ],
    "reg_date": "2026-02-15",
    "special_notes": "",
    "is_emailed": false,
    "status": "enrolled"
  },
  {
    "id": 110,
    "name": "Mark Arruda",
    "ptft": "PT",
    "paid": "yes",
    "enrollment": "yes",
    "parent": "Lisa Arruda",
    "email": "lisaamorim@yahoo.com",
    "phone": "617-438-7969",
    "age": 12,
    "city": "Salem",
    "sex": "M",
    "wr": "W & R",
    "allergies": "",
    "tshirt": "AM",
    "notes": "",
    "weeks": "3,4,5,6,7,8",
    "weeks_arr": [
      0,
      0,
      1,
      1,
      1,
      1,
      1,
      1
    ],
    "reg_date": "2026-02-26",
    "special_notes": "",
    "is_emailed": false,
    "status": "enrolled"
  },
  {
    "id": 111,
    "name": "Marley Houston",
    "ptft": "PT",
    "paid": "yes",
    "enrollment": "yes",
    "parent": "Alli Houston",
    "email": "alli.crabtree@gmail.com",
    "phone": "617-285-7330",
    "age": 5,
    "city": "North Andover",
    "sex": "F",
    "wr": "W & R",
    "allergies": "",
    "tshirt": "YS",
    "notes": "",
    "weeks": "1,2,6",
    "weeks_arr": [
      1,
      1,
      0,
      0,
      0,
      1,
      0,
      0
    ],
    "reg_date": "2026-01-06",
    "special_notes": "",
    "is_emailed": false,
    "status": "enrolled"
  },
  {
    "id": 112,
    "name": "Mason Vouris",
    "ptft": "PT",
    "paid": "yes",
    "enrollment": "yes",
    "parent": "Nicole Vouris",
    "email": "nicole.vouris@gmail.com",
    "phone": "978-905-5357",
    "age": 8,
    "city": "Salem",
    "sex": "M",
    "wr": "W & R",
    "allergies": "",
    "tshirt": "YS",
    "notes": "",
    "weeks": "1,6",
    "weeks_arr": [
      1,
      0,
      0,
      0,
      0,
      1,
      0,
      0
    ],
    "reg_date": "2026-01-19",
    "special_notes": "",
    "is_emailed": false,
    "status": "enrolled"
  },
  {
    "id": 113,
    "name": "Max Yeghiazarians",
    "ptft": "",
    "paid": "",
    "enrollment": "",
    "parent": "",
    "email": "",
    "phone": "",
    "age": 0,
    "city": "",
    "sex": "",
    "wr": "",
    "allergies": "",
    "tshirt": "",
    "notes": "",
    "weeks": "",
    "weeks_arr": [
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0
    ],
    "reg_date": "",
    "special_notes": "",
    "is_emailed": true,
    "status": "lead"
  },
  {
    "id": 114,
    "name": "Maxwell Hodgson",
    "ptft": "PT",
    "paid": "yes",
    "enrollment": "yes",
    "parent": "Megan Hodgson",
    "email": "levy.mega@gmail.com",
    "phone": "978-289-8507",
    "age": 6,
    "city": "North Andover",
    "sex": "M",
    "wr": "W & R",
    "allergies": "amoxicillin",
    "tshirt": "YM",
    "notes": "",
    "weeks": "3,5,6",
    "weeks_arr": [
      0,
      0,
      1,
      0,
      1,
      1,
      0,
      0
    ],
    "reg_date": "2026-01-06",
    "special_notes": "",
    "is_emailed": false,
    "status": "enrolled"
  },
  {
    "id": 115,
    "name": "Maya Vincent",
    "ptft": "PT",
    "paid": "yes",
    "enrollment": "yes",
    "parent": "Rebecca Vincent",
    "email": "rebecc5506@gmail.com",
    "phone": "508-725-1953",
    "age": 11,
    "city": "Methuen",
    "sex": "F",
    "wr": "W & R",
    "allergies": "",
    "tshirt": "AM",
    "notes": "",
    "weeks": "3,4,5,6,8",
    "weeks_arr": [
      0,
      0,
      1,
      1,
      1,
      1,
      0,
      1
    ],
    "reg_date": "2026-01-27",
    "special_notes": "",
    "is_emailed": false,
    "status": "enrolled"
  },
  {
    "id": 116,
    "name": "Michael Dardas",
    "ptft": "",
    "paid": "",
    "enrollment": "",
    "parent": "",
    "email": "",
    "phone": "",
    "age": 0,
    "city": "",
    "sex": "",
    "wr": "",
    "allergies": "",
    "tshirt": "",
    "notes": "",
    "weeks": "",
    "weeks_arr": [
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0
    ],
    "reg_date": "",
    "special_notes": "",
    "is_emailed": true,
    "status": "lead"
  },
  {
    "id": 117,
    "name": "Michael Freiner",
    "ptft": "",
    "paid": "",
    "enrollment": "",
    "parent": "",
    "email": "",
    "phone": "",
    "age": 0,
    "city": "",
    "sex": "",
    "wr": "",
    "allergies": "",
    "tshirt": "",
    "notes": "",
    "weeks": "",
    "weeks_arr": [
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0
    ],
    "reg_date": "",
    "special_notes": "",
    "is_emailed": true,
    "status": "lead"
  },
  {
    "id": 118,
    "name": "Mila Jordan",
    "ptft": "",
    "paid": "",
    "enrollment": "",
    "parent": "",
    "email": "",
    "phone": "",
    "age": 0,
    "city": "",
    "sex": "",
    "wr": "",
    "allergies": "",
    "tshirt": "",
    "notes": "",
    "weeks": "",
    "weeks_arr": [
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0
    ],
    "reg_date": "",
    "special_notes": "",
    "is_emailed": true,
    "status": "lead"
  },
  {
    "id": 119,
    "name": "Molly Early",
    "ptft": "PT",
    "paid": "yes",
    "enrollment": "yes",
    "parent": "Kathryn Early",
    "email": "katymearly@gmail.com",
    "phone": "978-257-7683",
    "age": 9,
    "city": "Atkinson",
    "sex": "F",
    "wr": "W & R",
    "allergies": "",
    "tshirt": "YL",
    "notes": "",
    "weeks": "2",
    "weeks_arr": [
      0,
      1,
      0,
      0,
      0,
      0,
      0,
      0
    ],
    "reg_date": "2026-01-06",
    "special_notes": "",
    "is_emailed": false,
    "status": "enrolled"
  },
  {
    "id": 120,
    "name": "Natalia Kelly",
    "ptft": "PT",
    "paid": "yes",
    "enrollment": "yes",
    "parent": "Jennie Kelly",
    "email": "jennielstone@comcast.net",
    "phone": "978-509-1749",
    "age": 10,
    "city": "North Andover",
    "sex": "F",
    "wr": "W & R",
    "allergies": "",
    "tshirt": "YL",
    "notes": "mom is medical director",
    "weeks": "1,2,3,4,6,7",
    "weeks_arr": [
      1,
      1,
      1,
      1,
      0,
      1,
      1,
      0
    ],
    "reg_date": "2026-01-08",
    "special_notes": "",
    "is_emailed": false,
    "status": "enrolled"
  },
  {
    "id": 121,
    "name": "Neil Kamolsiri",
    "ptft": "",
    "paid": "",
    "enrollment": "",
    "parent": "",
    "email": "",
    "phone": "",
    "age": 0,
    "city": "",
    "sex": "",
    "wr": "",
    "allergies": "",
    "tshirt": "",
    "notes": "",
    "weeks": "",
    "weeks_arr": [
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0
    ],
    "reg_date": "",
    "special_notes": "",
    "is_emailed": true,
    "status": "lead"
  },
  {
    "id": 122,
    "name": "Noah Bretas",
    "ptft": "",
    "paid": "",
    "enrollment": "",
    "parent": "",
    "email": "",
    "phone": "",
    "age": 0,
    "city": "",
    "sex": "",
    "wr": "",
    "allergies": "",
    "tshirt": "",
    "notes": "",
    "weeks": "",
    "weeks_arr": [
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0
    ],
    "reg_date": "",
    "special_notes": "",
    "is_emailed": true,
    "status": "lead"
  },
  {
    "id": 123,
    "name": "Noah Douglass",
    "ptft": "",
    "paid": "",
    "enrollment": "",
    "parent": "",
    "email": "",
    "phone": "",
    "age": 0,
    "city": "",
    "sex": "",
    "wr": "",
    "allergies": "",
    "tshirt": "",
    "notes": "",
    "weeks": "",
    "weeks_arr": [
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0
    ],
    "reg_date": "",
    "special_notes": "",
    "is_emailed": true,
    "status": "lead"
  },
  {
    "id": 124,
    "name": "Nora Connolly",
    "ptft": "PT",
    "paid": "yes",
    "enrollment": "yes",
    "parent": "Michelle Connolly",
    "email": "mhoward411@gmail.com",
    "phone": "978-994-3945",
    "age": 10,
    "city": "North Andover",
    "sex": "F",
    "wr": "W & R",
    "allergies": "",
    "tshirt": "YM",
    "notes": "taking fluoxetine",
    "weeks": "2",
    "weeks_arr": [
      0,
      1,
      0,
      0,
      0,
      0,
      0,
      0
    ],
    "reg_date": "2026-03-19",
    "special_notes": "",
    "is_emailed": false,
    "status": "enrolled"
  },
  {
    "id": 125,
    "name": "Nora Foster",
    "ptft": "PT",
    "paid": "yes",
    "enrollment": "no",
    "parent": "Shaunna Foster",
    "email": "schovorka@gmail.com",
    "phone": "402-320-7905",
    "age": 0,
    "city": "North Andover",
    "sex": "F",
    "wr": "W & R",
    "allergies": "",
    "tshirt": "YM",
    "notes": "",
    "weeks": "4,5",
    "weeks_arr": [
      0,
      0,
      0,
      1,
      1,
      0,
      0,
      0
    ],
    "reg_date": "2026-02-01",
    "special_notes": "",
    "is_emailed": true,
    "status": "enrolled"
  },
  {
    "id": 126,
    "name": "Nora Howell",
    "ptft": "PT",
    "paid": "yes",
    "enrollment": "yes",
    "parent": "Alexandra Howell",
    "email": "alexandra.d.howell@gmail.com",
    "phone": "860-989-3871",
    "age": 8,
    "city": "North Andover",
    "sex": "F",
    "wr": "W & R",
    "allergies": "",
    "tshirt": "YL",
    "notes": "",
    "weeks": "1,2,3",
    "weeks_arr": [
      1,
      1,
      1,
      0,
      0,
      0,
      0,
      0
    ],
    "reg_date": "2026-01-06",
    "special_notes": "",
    "is_emailed": false,
    "status": "enrolled"
  },
  {
    "id": 127,
    "name": "Nora Lentine (Taylor)",
    "ptft": "PT",
    "paid": "no",
    "enrollment": "no",
    "parent": "Chris Lentine",
    "email": "chrislentine@gmail.com",
    "phone": "781-726-2920",
    "age": 6,
    "city": "Methuen",
    "sex": "F",
    "wr": "W & R",
    "allergies": "",
    "tshirt": "YM",
    "notes": "",
    "weeks": "1,2,3,5,6,7,8",
    "weeks_arr": [
      1,
      1,
      1,
      0,
      1,
      1,
      1,
      1
    ],
    "reg_date": "2026-03-11",
    "special_notes": "",
    "is_emailed": false,
    "status": "enrolled"
  },
  {
    "id": 128,
    "name": "Nori Niblack",
    "ptft": "PT",
    "paid": "yes",
    "enrollment": "yes",
    "parent": "Emily Segura",
    "email": "seguraemily@gmail.com",
    "phone": "347-839-6692",
    "age": 5,
    "city": "Haverhill",
    "sex": "F",
    "wr": "W & R",
    "allergies": "",
    "tshirt": "YS",
    "notes": "",
    "weeks": "3,4,6,7,8",
    "weeks_arr": [
      0,
      0,
      1,
      1,
      0,
      1,
      1,
      1
    ],
    "reg_date": "2026-03-18",
    "special_notes": "",
    "is_emailed": false,
    "status": "enrolled"
  },
  {
    "id": 129,
    "name": "Olivia Comee",
    "ptft": "",
    "paid": "",
    "enrollment": "",
    "parent": "",
    "email": "",
    "phone": "",
    "age": 0,
    "city": "",
    "sex": "",
    "wr": "",
    "allergies": "",
    "tshirt": "",
    "notes": "",
    "weeks": "",
    "weeks_arr": [
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0
    ],
    "reg_date": "",
    "special_notes": "",
    "is_emailed": true,
    "status": "lead"
  },
  {
    "id": 130,
    "name": "Olivia Parkes",
    "ptft": "FT",
    "paid": "yes",
    "enrollment": "yes",
    "parent": "Krystle Parkes",
    "email": "kparkes531@gmail.com",
    "phone": "978-979-4502",
    "age": 9,
    "city": "Haverhill",
    "sex": "F",
    "wr": "W & R",
    "allergies": "",
    "tshirt": "YXL",
    "notes": "",
    "weeks": "1,2,3,4,5,6,7,8",
    "weeks_arr": [
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1
    ],
    "reg_date": "2026-01-09",
    "special_notes": "",
    "is_emailed": false,
    "status": "enrolled"
  },
  {
    "id": 131,
    "name": "Philomena (Mena) Gleason",
    "ptft": "PT",
    "paid": "no",
    "enrollment": "",
    "parent": "Kristen Vadala",
    "email": "vadalak@gmail.com",
    "phone": "310-490-8915",
    "age": 0,
    "city": "Salem",
    "sex": "F",
    "wr": "R",
    "allergies": "",
    "tshirt": "YXS",
    "notes": "",
    "weeks": "1,3,5,7",
    "weeks_arr": [
      1,
      0,
      1,
      0,
      1,
      0,
      1,
      0
    ],
    "reg_date": "",
    "special_notes": "",
    "is_emailed": false,
    "status": "enrolled"
  },
  {
    "id": 132,
    "name": "Quinn Matosic",
    "ptft": "PT",
    "paid": "yes",
    "enrollment": "no",
    "parent": "Maura Matosic",
    "email": "maura.allen@gmail.com",
    "phone": "860-212-8627",
    "age": 0,
    "city": "Methuen",
    "sex": "M",
    "wr": "W & R",
    "allergies": "",
    "tshirt": "YS",
    "notes": "",
    "weeks": "3,8",
    "weeks_arr": [
      0,
      0,
      1,
      0,
      0,
      0,
      0,
      1
    ],
    "reg_date": "2026-01-19",
    "special_notes": "",
    "is_emailed": true,
    "status": "enrolled"
  },
  {
    "id": 133,
    "name": "Reagan Slein",
    "ptft": "",
    "paid": "",
    "enrollment": "",
    "parent": "",
    "email": "",
    "phone": "",
    "age": 0,
    "city": "",
    "sex": "",
    "wr": "",
    "allergies": "",
    "tshirt": "",
    "notes": "",
    "weeks": "",
    "weeks_arr": [
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0
    ],
    "reg_date": "",
    "special_notes": "",
    "is_emailed": true,
    "status": "lead"
  },
  {
    "id": 134,
    "name": "Reese Abruzzese",
    "ptft": "PT",
    "paid": "yes",
    "enrollment": "yes",
    "parent": "Devon Abruzzese",
    "email": "devonh86@gmail.com",
    "phone": "609-954-2309",
    "age": 7,
    "city": "Methuen",
    "sex": "F",
    "wr": "W & R",
    "allergies": "amoxicilin",
    "tshirt": "YM",
    "notes": "",
    "weeks": "4",
    "weeks_arr": [
      0,
      0,
      0,
      1,
      0,
      0,
      0,
      0
    ],
    "reg_date": "2026-03-09",
    "special_notes": "",
    "is_emailed": false,
    "status": "enrolled"
  },
  {
    "id": 135,
    "name": "Riley Creamer",
    "ptft": "PT",
    "paid": "yes",
    "enrollment": "yes",
    "parent": "Brianne Creamer",
    "email": "brianne.creamer@hotmail.com",
    "phone": "603-674-4218",
    "age": 10,
    "city": "Salem",
    "sex": "F",
    "wr": "W & R",
    "allergies": "",
    "tshirt": "YM",
    "notes": "",
    "weeks": "1,2,3,4,6,7",
    "weeks_arr": [
      1,
      1,
      1,
      1,
      0,
      1,
      1,
      0
    ],
    "reg_date": "2026-01-17",
    "special_notes": "",
    "is_emailed": false,
    "status": "enrolled"
  },
  {
    "id": 136,
    "name": "River Dolan",
    "ptft": "PT",
    "paid": "yes",
    "enrollment": "yes",
    "parent": "Alyssa Dolan",
    "email": "alyssa.rastiello@gmail.com",
    "phone": "978-684-2636",
    "age": 8,
    "city": "Methuen",
    "sex": "M",
    "wr": "W & R",
    "allergies": "",
    "tshirt": "YM",
    "notes": "",
    "weeks": "3",
    "weeks_arr": [
      0,
      0,
      1,
      0,
      0,
      0,
      0,
      0
    ],
    "reg_date": "2026-02-04",
    "special_notes": "",
    "is_emailed": false,
    "status": "enrolled"
  },
  {
    "id": 137,
    "name": "Roman Kelly",
    "ptft": "PT",
    "paid": "yes",
    "enrollment": "yes",
    "parent": "Jennie Kelly",
    "email": "jennielstone@comcast.net",
    "phone": "978-509-1749",
    "age": 10,
    "city": "North Andover",
    "sex": "M",
    "wr": "W & R",
    "allergies": "",
    "tshirt": "YL",
    "notes": "mom is medical director",
    "weeks": "1,2,3,4,6,7",
    "weeks_arr": [
      1,
      1,
      1,
      1,
      0,
      1,
      1,
      0
    ],
    "reg_date": "2026-01-08",
    "special_notes": "",
    "is_emailed": false,
    "status": "enrolled"
  },
  {
    "id": 138,
    "name": "Roman Sambataro",
    "ptft": "",
    "paid": "",
    "enrollment": "",
    "parent": "",
    "email": "",
    "phone": "",
    "age": 0,
    "city": "",
    "sex": "",
    "wr": "",
    "allergies": "",
    "tshirt": "",
    "notes": "",
    "weeks": "",
    "weeks_arr": [
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0
    ],
    "reg_date": "",
    "special_notes": "",
    "is_emailed": true,
    "status": "lead"
  },
  {
    "id": 139,
    "name": "Roman Sargent",
    "ptft": "PT",
    "paid": "yes",
    "enrollment": "yes",
    "parent": "Lindsey Sargent",
    "email": "lsargent88@gmail.com",
    "phone": "603-930-6638",
    "age": 6,
    "city": "Salem",
    "sex": "M",
    "wr": "W & R",
    "allergies": "",
    "tshirt": "YM",
    "notes": "",
    "weeks": "1,4,5,6,7,8",
    "weeks_arr": [
      1,
      0,
      0,
      1,
      1,
      1,
      1,
      1
    ],
    "reg_date": "2026-02-09",
    "special_notes": "",
    "is_emailed": false,
    "status": "enrolled"
  },
  {
    "id": 140,
    "name": "Ruby Weiner",
    "ptft": "PT",
    "paid": "yes",
    "enrollment": "yes",
    "parent": "Benjamin Weiner",
    "email": "bweiner10@yahoo.com",
    "phone": "978-502-5093",
    "age": 10,
    "city": "North Andover",
    "sex": "F",
    "wr": "W & R",
    "allergies": "",
    "tshirt": "YL",
    "notes": "",
    "weeks": "4,5",
    "weeks_arr": [
      0,
      0,
      0,
      1,
      1,
      0,
      0,
      0
    ],
    "reg_date": "2026-01-21",
    "special_notes": "",
    "is_emailed": false,
    "status": "enrolled"
  },
  {
    "id": 141,
    "name": "Ryan Murphy",
    "ptft": "PT",
    "paid": "yes",
    "enrollment": "yes",
    "parent": "Karen Murphy",
    "email": "karenls14@gmail.com",
    "phone": "585-269-8720",
    "age": 13,
    "city": "Billerica",
    "sex": "M",
    "wr": "W & R",
    "allergies": "",
    "tshirt": "AM",
    "notes": "",
    "weeks": "2,3",
    "weeks_arr": [
      0,
      1,
      1,
      0,
      0,
      0,
      0,
      0
    ],
    "reg_date": "2026-03-22",
    "special_notes": "",
    "is_emailed": false,
    "status": "enrolled"
  },
  {
    "id": 142,
    "name": "Samuel Habib",
    "ptft": "",
    "paid": "",
    "enrollment": "",
    "parent": "",
    "email": "",
    "phone": "",
    "age": 0,
    "city": "",
    "sex": "",
    "wr": "",
    "allergies": "",
    "tshirt": "",
    "notes": "",
    "weeks": "",
    "weeks_arr": [
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0
    ],
    "reg_date": "",
    "special_notes": "",
    "is_emailed": true,
    "status": "lead"
  },
  {
    "id": 143,
    "name": "Scarlett Plourde",
    "ptft": "PT",
    "paid": "yes",
    "enrollment": "yes",
    "parent": "Jennifer Plourde",
    "email": "jlplourde31@gmail.com",
    "phone": "978-257-1146",
    "age": 7,
    "city": "Salem",
    "sex": "F",
    "wr": "R",
    "allergies": "",
    "tshirt": "YM",
    "notes": "",
    "weeks": "2",
    "weeks_arr": [
      0,
      1,
      0,
      0,
      0,
      0,
      0,
      0
    ],
    "reg_date": "2026-01-08",
    "special_notes": "",
    "is_emailed": true,
    "status": "enrolled"
  },
  {
    "id": 144,
    "name": "Sebastian Muso",
    "ptft": "FT",
    "paid": "yes",
    "enrollment": "yes",
    "parent": "Ergen Muso",
    "email": "emuso85@gmail.com",
    "phone": "727-288-7442",
    "age": 11,
    "city": "Windham",
    "sex": "M",
    "wr": "W & R",
    "allergies": "",
    "tshirt": "YL",
    "notes": "",
    "weeks": "1,2,3,4,5,6,7,8",
    "weeks_arr": [
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1
    ],
    "reg_date": "2026-01-10",
    "special_notes": "",
    "is_emailed": false,
    "status": "enrolled"
  },
  {
    "id": 145,
    "name": "Shray Israni",
    "ptft": "PT",
    "paid": "yes",
    "enrollment": "yes",
    "parent": "Jenna Israni",
    "email": "paddoljl@gmail.com",
    "phone": "617-755-7531",
    "age": 9,
    "city": "North Andover",
    "sex": "M",
    "wr": "W & R",
    "allergies": "",
    "tshirt": "YM",
    "notes": "",
    "weeks": "6,7",
    "weeks_arr": [
      0,
      0,
      0,
      0,
      0,
      1,
      1,
      0
    ],
    "reg_date": "2026-01-20",
    "special_notes": "",
    "is_emailed": false,
    "status": "enrolled"
  },
  {
    "id": 146,
    "name": "Stella Zang",
    "ptft": "PT",
    "paid": "no",
    "enrollment": "no",
    "parent": "Elana Zang",
    "email": "elana.zang@gmaiil.com",
    "phone": "973-534-6296",
    "age": 7,
    "city": "North Andover",
    "sex": "F",
    "wr": "W & R",
    "allergies": "",
    "tshirt": "YM",
    "notes": "",
    "weeks": "3,?",
    "weeks_arr": [
      0,
      0,
      1,
      0,
      0,
      0,
      0,
      0
    ],
    "reg_date": "",
    "special_notes": "",
    "is_emailed": true,
    "status": "enrolled"
  },
  {
    "id": 147,
    "name": "Summer Dolan",
    "ptft": "",
    "paid": "",
    "enrollment": "",
    "parent": "",
    "email": "",
    "phone": "",
    "age": 0,
    "city": "",
    "sex": "",
    "wr": "",
    "allergies": "",
    "tshirt": "",
    "notes": "",
    "weeks": "",
    "weeks_arr": [
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0
    ],
    "reg_date": "",
    "special_notes": "",
    "is_emailed": true,
    "status": "lead"
  },
  {
    "id": 148,
    "name": "Theo Sanchez",
    "ptft": "",
    "paid": "",
    "enrollment": "",
    "parent": "",
    "email": "",
    "phone": "",
    "age": 0,
    "city": "",
    "sex": "",
    "wr": "",
    "allergies": "",
    "tshirt": "",
    "notes": "",
    "weeks": "",
    "weeks_arr": [
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0
    ],
    "reg_date": "",
    "special_notes": "",
    "is_emailed": true,
    "status": "lead"
  },
  {
    "id": 149,
    "name": "Thomas Broderick",
    "ptft": "",
    "paid": "",
    "enrollment": "",
    "parent": "",
    "email": "",
    "phone": "",
    "age": 0,
    "city": "",
    "sex": "",
    "wr": "",
    "allergies": "",
    "tshirt": "",
    "notes": "",
    "weeks": "",
    "weeks_arr": [
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0
    ],
    "reg_date": "",
    "special_notes": "",
    "is_emailed": true,
    "status": "lead"
  },
  {
    "id": 150,
    "name": "Tyler Howell",
    "ptft": "PT",
    "paid": "yes",
    "enrollment": "yes",
    "parent": "Alexandra Howell",
    "email": "alexandra.d.howell@gmail.com",
    "phone": "860-989-3871",
    "age": 6,
    "city": "North Andover",
    "sex": "M",
    "wr": "W & R",
    "allergies": "",
    "tshirt": "YS",
    "notes": "",
    "weeks": "1,2,3,4,6",
    "weeks_arr": [
      1,
      1,
      1,
      1,
      0,
      1,
      0,
      0
    ],
    "reg_date": "2026-01-06",
    "special_notes": "",
    "is_emailed": false,
    "status": "enrolled"
  },
  {
    "id": 151,
    "name": "Valentino Perdomo",
    "ptft": "",
    "paid": "",
    "enrollment": "",
    "parent": "",
    "email": "",
    "phone": "",
    "age": 0,
    "city": "",
    "sex": "",
    "wr": "",
    "allergies": "",
    "tshirt": "",
    "notes": "",
    "weeks": "",
    "weeks_arr": [
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0
    ],
    "reg_date": "",
    "special_notes": "",
    "is_emailed": true,
    "status": "lead"
  },
  {
    "id": 152,
    "name": "Viktor Saul",
    "ptft": "PT",
    "paid": "yes",
    "enrollment": "yes",
    "parent": "David Saul",
    "email": "bdsaul@gmail.com",
    "phone": "774-279-1157",
    "age": 10,
    "city": "Lawrence",
    "sex": "M",
    "wr": "W & R",
    "allergies": "",
    "tshirt": "AXS",
    "notes": "",
    "weeks": "3,4",
    "weeks_arr": [
      0,
      0,
      1,
      1,
      0,
      0,
      0,
      0
    ],
    "reg_date": "2026-01-27",
    "special_notes": "",
    "is_emailed": false,
    "status": "enrolled"
  },
  {
    "id": 153,
    "name": "Vinny Romano",
    "ptft": "",
    "paid": "",
    "enrollment": "",
    "parent": "",
    "email": "",
    "phone": "",
    "age": 0,
    "city": "",
    "sex": "",
    "wr": "",
    "allergies": "",
    "tshirt": "",
    "notes": "",
    "weeks": "",
    "weeks_arr": [
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0
    ],
    "reg_date": "",
    "special_notes": "",
    "is_emailed": true,
    "status": "lead"
  },
  {
    "id": 154,
    "name": "Violet Affronti",
    "ptft": "PT",
    "paid": "yes",
    "enrollment": "yes",
    "parent": "Heidi Affronti",
    "email": "heidi.affronti@gmail.com",
    "phone": "207-522-4132",
    "age": 5,
    "city": "Salem",
    "sex": "F",
    "wr": "W & R",
    "allergies": "",
    "tshirt": "YXS",
    "notes": "",
    "weeks": "3,6",
    "weeks_arr": [
      0,
      0,
      1,
      0,
      0,
      1,
      0,
      0
    ],
    "reg_date": "2026-01-24",
    "special_notes": "",
    "is_emailed": false,
    "status": "enrolled"
  },
  {
    "id": 155,
    "name": "Vivienne Hannon",
    "ptft": "FT",
    "paid": "yes",
    "enrollment": "yes",
    "parent": "Krista Hannon",
    "email": "kristalhannon@gmail.com",
    "phone": "603-560-6189",
    "age": 8,
    "city": "Salem",
    "sex": "F",
    "wr": "W & R",
    "allergies": "mosquitoes ",
    "tshirt": "YS",
    "notes": "",
    "weeks": "1,2,3,4,6,7,8",
    "weeks_arr": [
      1,
      1,
      1,
      1,
      0,
      1,
      1,
      1
    ],
    "reg_date": "2026-01-31",
    "special_notes": "",
    "is_emailed": false,
    "status": "enrolled"
  },
  {
    "id": 156,
    "name": "Wilson Touma",
    "ptft": "PT",
    "paid": "yes",
    "enrollment": "yes",
    "parent": "Allison Touma",
    "email": "amarcotte77@gmail.com",
    "phone": "978-758-3505",
    "age": 8,
    "city": "Salem",
    "sex": "M",
    "wr": "W & R",
    "allergies": "",
    "tshirt": "YS",
    "notes": "",
    "weeks": "3,6",
    "weeks_arr": [
      0,
      0,
      1,
      0,
      0,
      1,
      0,
      0
    ],
    "reg_date": "2026-02-03",
    "special_notes": "",
    "is_emailed": false,
    "status": "enrolled"
  },
  {
    "id": 157,
    "name": "Zayn Niblack",
    "ptft": "PT",
    "paid": "yes",
    "enrollment": "yes",
    "parent": "Emily Segura",
    "email": "seguraemily@gmail.com",
    "phone": "347-839-6692",
    "age": 8,
    "city": "Haverhill",
    "sex": "M",
    "wr": "W & R",
    "allergies": "",
    "tshirt": "YM",
    "notes": "",
    "weeks": "3,4,6,7,8",
    "weeks_arr": [
      0,
      0,
      1,
      1,
      0,
      1,
      1,
      1
    ],
    "reg_date": "2026-03-18",
    "special_notes": "",
    "is_emailed": false,
    "status": "enrolled"
  },
  {
    "id": 158,
    "name": "Zoey Rivera",
    "ptft": "PT",
    "paid": "yes",
    "enrollment": "yes",
    "parent": "Jen Rivera",
    "email": "jennifermorency@gmail.com",
    "phone": "978-609-4170",
    "age": 0,
    "city": "Haverhill",
    "sex": "F",
    "wr": "W",
    "allergies": "",
    "tshirt": "",
    "notes": "",
    "weeks": "1,2,3,4,6",
    "weeks_arr": [
      1,
      1,
      1,
      1,
      0,
      1,
      0,
      0
    ],
    "reg_date": "2026-02-01",
    "special_notes": "",
    "is_emailed": true,
    "status": "enrolled"
  },
  {
    "id": 159,
    "name": "Zya Quezada",
    "ptft": "FT",
    "paid": "yes",
    "enrollment": "yes",
    "parent": "Shaina Santos",
    "email": "shai2487@yahoo.com",
    "phone": "978-305-5528",
    "age": 7,
    "city": "Lawrence",
    "sex": "F",
    "wr": "W & R",
    "allergies": "",
    "tshirt": "YM",
    "notes": "",
    "weeks": "1,2,3,4,5,6,7,8",
    "weeks_arr": [
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1
    ],
    "reg_date": "2026-03-18",
    "special_notes": "",
    "is_emailed": false,
    "status": "enrolled"
  }
];

seedCampers(camperData);

const insertComp = db.prepare(`
  INSERT INTO comps (name,paid,parent,email,phone,age,city,sex,allergies,weeks,status)
  VALUES (@name,@paid,@parent,@email,@phone,@age,@city,@sex,@allergies,@weeks,@status)
`);

const compData = [
  {
    "id": 205,
    "name": "Brendan Maxwell",
    "paid": "C",
    "parent": "Kristen Maxwell",
    "email": "KayC1030@yahoo.com",
    "phone": "339-224-3144",
    "age": 9,
    "city": "Methuen",
    "sex": "M",
    "allergies": "PEANUTS",
    "weeks": "",
    "status": "comp"
  },
  {
    "id": 206,
    "name": "Peyton Maxwell",
    "paid": "C",
    "parent": "Kristen Maxwell",
    "email": "KayC1030@yahoo.com",
    "phone": "339-224-3144",
    "age": 14,
    "city": "Methuen",
    "sex": "F",
    "allergies": "",
    "weeks": "",
    "status": "comp"
  },
  {
    "id": 207,
    "name": "Cayden Mustapha",
    "paid": "C",
    "parent": "Michael Mustapha",
    "email": "mikemcabinetdepot@gmail.com",
    "phone": "9788091058",
    "age": 9,
    "city": "Methuen",
    "sex": "M",
    "allergies": "Tree Nuts",
    "weeks": "",
    "status": "comp"
  },
  {
    "id": 208,
    "name": "Leo Micalizzi",
    "paid": "C",
    "parent": "Kristin Micalizzi",
    "email": "",
    "phone": "9782906657",
    "age": 13,
    "city": "Boxford",
    "sex": "M",
    "allergies": "",
    "weeks": "",
    "status": "comp"
  },
  {
    "id": 209,
    "name": "Will Micalizzi",
    "paid": "C",
    "parent": "Kristin Micalizzi",
    "email": "",
    "phone": "9782906657",
    "age": 11,
    "city": "Boxford",
    "sex": "M",
    "allergies": "",
    "weeks": "",
    "status": "comp"
  },
  {
    "id": 210,
    "name": "Cohen Payson",
    "paid": "C",
    "parent": "Melissa Payson",
    "email": "paysonservices@gmail.com",
    "phone": "9788355175",
    "age": 11,
    "city": "Methuen",
    "sex": "M",
    "allergies": "No",
    "weeks": "",
    "status": "comp"
  },
  {
    "id": 211,
    "name": "Sutton Payson",
    "paid": "C",
    "parent": "Melissa Payson",
    "email": "paysonservices@gmail.com",
    "phone": "9788355175",
    "age": 9,
    "city": "Methuen",
    "sex": "M",
    "allergies": "No",
    "weeks": "",
    "status": "comp"
  },
  {
    "id": 212,
    "name": "Jameson Dalrymple",
    "paid": "C",
    "parent": "Chelsea Dietrich",
    "email": "chelsea_dietrich22@yahoo.com",
    "phone": "9787718413",
    "age": 9,
    "city": "Methuen",
    "sex": "M",
    "allergies": "No",
    "weeks": "1, 5, 6, 7, 8",
    "status": "comp"
  },
  {
    "id": 215,
    "name": "Brody Alicandro",
    "paid": "Unknown",
    "parent": "Brittany Alicandro",
    "email": "bnmed1121@yahoo.com",
    "phone": "9782659106",
    "age": 11,
    "city": "Salem",
    "sex": "M",
    "allergies": "No",
    "weeks": "1, 3, 5, 6, 7, 8",
    "status": "unregistered"
  },
  {
    "id": 216,
    "name": "Braden Alicandro",
    "paid": "Unknown",
    "parent": "Brittany Alicandro",
    "email": "bnmed1121@yahoo.com",
    "phone": "9782659106",
    "age": 11,
    "city": "Salem",
    "sex": "M",
    "allergies": "No",
    "weeks": "1, 3, 5, 6, 7, 8",
    "status": "unregistered"
  },
  {
    "id": 217,
    "name": "Blake Alicandro",
    "paid": "Unknown",
    "parent": "Brittany Alicandro",
    "email": "bnmed1121@yahoo.com",
    "phone": "9782659106",
    "age": 7,
    "city": "Salem",
    "sex": "M ",
    "allergies": "No",
    "weeks": "1, 3, 5, 6, 7, 8",
    "status": "unregistered"
  }
];
for (const c of compData) {
  insertComp.run({ name:c.name, paid:c.paid||'C', parent:c.parent||'', email:c.email||'', phone:c.phone||'', age:c.age||0, city:c.city||'', sex:c.sex||'', allergies:c.allergies||'', weeks:c.weeks||'', status:c.status||'comp' });
}

const count = db.prepare('SELECT COUNT(*) as c FROM campers').get().c;
console.log('Done! Seeded ' + count + ' campers + ' + compData.length + ' comps.');
db.close();